### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by sober-wang** [apache/apisix-ingress-controller#100]
the ingress-controller pods start have error.
standard_init_linux.go:211: exec user process caused "no such file or directory"

ingress-controller : v0.1.0
k8s version: 1.18.2

```yaml
---
# my rbac binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apisix-view-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apisix-view-clusterrole
subjects:
- kind: ServiceAccount
  name: apisix-view-serviceaccount
  namespace: myns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apisix-view-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixroutes
  - apisixupstreams
  - apisixservices
  verbs:
  - get
  - list
  - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apisix-view-serviceaccount
  namespace: myns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: myns
data:
  SYSLOG_HOST: 127.0.0.1
  APISIX_BASE_URL: "http://apisix.myns.svc.cluster.local:9180/apisix/admin"
  ENV: "prod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-controller
  namespace: myns
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: apisix-ingress-controller
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app: apisix-ingress-controller
        tier: backend
    spec:
      hostNetwork: true
      containers:
      - envFrom:
        - configMapRef:
            name: apisix-config
        image: myimage/apisix-ingress-controller:v0.1.0
        imagePullPolicy: IfNotPresent
        name: ingress-controller
        ports:
        - containerPort: 8080
          hostPort: 8080
      terminationGracePeriodSeconds: 60
      serviceAccountName: apisix-view-serviceaccount
```

the images is Docker build from Dockerfile.
