### ISSUE TITLE
request help: Configure ApisixUpstream by apisix-ingress-controller

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix-ingress-controller#1013]
### Issue description

What should I do if I want to configure upstream. Configuring it with dashboard causes the ingress-controller to report an error, but there is no such crd
![image](https://user-images.githubusercontent.com/92301646/167621762-8a5778a3-b5d8-4b6a-96da-794f6a258ed3.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.4.1
- your Kubernetes cluster version (output of kubectl version):1.18
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):Linux

**Comment by tao12345666333** [comment]
you can create your own ApisixUpstream resource.

plz see https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/concepts/apisix_upstream.md

**Comment by GhangZh** [comment]
Okay, I understand, I can configure it separately for special needs

**Comment by tao12345666333** [comment]
yep

**Comment by tao12345666333** [comment]
@GhangZh I see you reopened this question, was it a mistake?

**Comment by GhangZh** [comment]
When I wanted to use traffic-spilit according to the documentation, I found that it did not take effect after creating au. The configuration is as follows
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: reviews
  namespace: bookinfo
spec:
  subsets:
  - name: reviews-v1
    labels:
      app: reviews
      version: v1
  - name: reviews-v2
    labels:
      app: reviews
      version: v1
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: bookinfo
  namespace: bookinfo
spec:
  http:
  - backends:
    - serviceName: reviews
      servicePort: 9080
      subset: reviews-v1
      weight: 50
    - serviceName: reviews
      servicePort: 9080
      subset: reviews-v2
      weight: 50
    match:
      hosts:
      - bookinfo.com
      paths:
      - /*
    name: reviews
```
![image](https://user-images.githubusercontent.com/92301646/168027717-7dffd28e-b8bf-48b5-833a-98a100d48e66.png)
