### ISSUE TITLE
request help: failed to translate ApisixTls	{"error": "secret \"secret-name\" not found"

### ISSUE THREAD

**Issue by actliboy** [apache/apisix-ingress-controller#1038]
### Issue description

the secret can't found.

### Environment

helm charts apisix-0.9.3 apisix-ingress-controller-0.9.2
```
kubectl create secret tls secret-name -n default --cert=tls.crt --key=tls.key
kubectl apply -f - <<EOF
apiVersion: apisix.apache.org/v2beta3
kind: ApisixTls
metadata:
  name: secret-name
  namespace: default
spec:
  hosts:
    - secret.name
  secret:
    name: secret-name
    namespace: deafult
EOF
```
