### ISSUE TITLE
request help:  annotations about whitelist doesn't take effort

### ISSUE THREAD

**Issue by ddlinlin** [apache/apisix-ingress-controller#1048]
### Issue description

I set a route with ip-restriction via annotations like:

```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: apisix-route
  namespace: apisix
  annotations:
    k8s.apisix.apache.org/whitelist-source-range: 123.123.123.123
spec:
    http:
    - name: stg-admin
      match:
           hosts:
           - test.com.cn
           paths:
           - "/test/*"
 backends:
     - serviceName: test-svc
       servicePort: 8060
       resolveGranularity: service
```
----
ip-restriction does not take effort.
but it works when i update the yaml file like:

```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: apisix-route
  namespace: apisix
spec:
  http:
  - name: stg-admin
    match:
      hosts:
      - test.com.cn
      paths:
      - "/test/*"
 backends:
     - serviceName: test-svc
       servicePort: 8060
       resolveGranularity: service
 plugins:
 -  name:   ip-restriction
    enable:  true
    config:
        whitelist:
         - "123.123.123.123"
```
 --------

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): apache/apisix-ingress-controller:1.4.0
- your Kubernetes cluster version (output of kubectl version): 1.20.11
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
