### ISSUE TITLE
bug: Deleting `ApisixRoute` will delete only one `upstream`.

### ISSUE THREAD

**Issue by AlinsRan** [apache/apisix-ingress-controller#1050]
### Issue description

When `ApisixRoute` is configured with multiple services, multiple `upstream` of the same quantity will be created. When `ApisixRoute` is deleted, only one `upstream` will be deleted.

**In fact, redundant upstream has no impact on usage.**

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):  
![image](https://user-images.githubusercontent.com/79972061/170663676-016818f5-129d-45e6-8492-8365f0916791.png)
- your Kubernetes cluster version (output of kubectl version):  
![image](https://user-images.githubusercontent.com/79972061/170663597-b41d3433-559d-4324-98dc-fecb463d6b00.png)
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):  
![image](https://user-images.githubusercontent.com/79972061/170663315-fe2dd093-ef15-4290-bc60-0065fdaf7035.png)

### Minimal test code / Steps to reproduce

1. Create ApisxiRoute:

```shell
kubectl apply -f config.yaml
```

```yaml
#config.yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
 name: httpbin-route
spec:
 http:
 - name: rule1
   match:
     hosts:
     - httpbin.org
     paths:
       - /ip
   backends:
   - serviceName: httpbin-service-e2e-test
     servicePort: 80
   - serviceName: httpbin
     servicePort: 80
   - serviceName: httpbin2
     servicePort: 80
```

**upstream count=3**

![image](https://user-images.githubusercontent.com/79972061/170661760-2f28df9b-4142-496a-9acb-d3c92b016db8.png)

2. Delete ApisixRoute:

```shell
kubectl delete -f config.yaml
```
**upstream count=2**

![image](https://user-images.githubusercontent.com/79972061/170661968-ddd9141f-06dd-461e-badd-9fdac636210e.png)

### Actual result

upstream count=2

### Expected result

upstream count=0
