### ISSUE TITLE
docs: how to get started

### ISSUE THREAD

**Issue by vcqr** [apache/apisix-ingress-controller#1065]
### Issue description

<img width="818" alt="image" src="https://user-images.githubusercontent.com/3401237/171871543-ad9ae496-f08a-4ea4-bd83-6d8a95ea76f9.png">

Reference documentation:
https://apisix.apache.org/docs/ingress-controller/design

error: resource mapping not found for name: "demo" namespace: "demo-route" from "apisix-demo.yml": no matches for kind "ApisixRoute" in version "apisix.apache.org/v1"
ensure CRDs are installed first

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):none
- your Kubernetes cluster version (output of kubectl version): none
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):none

### Minimal test code / Steps to reproduce

kubectl apply -f apisix-demo.yml

``` yml
apiVersion: apisix.apache.org/v1
kind: ApisixRoute
metadata:
  name: demo
  namespace: demo-route
spec:
  rules: 
  - host: demo.com
    http: 
      paths: 
      - backend:
          serviceName: nginx-deployment
          ervicePort: 8888
        path: /demo*
```

### Actual result

none

### Error log

error: resource mapping not found for name: "demo" namespace: "demo-route" from "apisix-demo.yml": no matches for kind "ApisixRoute" in version "apisix.apache.org/v1"
