### ISSUE TITLE
request help:  can't create ApisixTls

### ISSUE THREAD

**Issue by haohello** [apache/apisix-ingress-controller#1083]
### Issue description

Run the command `kubectl apply -f` with the filename of the following content, and gets the error message as shown in the screenshot below.
```yaml
apiVersion: apisix.apache.org/v1
kind: ApisixTls
metadata:
  name: code-devtaoism-tls
spec:
  hosts:
  - code.devtaoism.com
  secret:
    name: code-devtaoism-acme-crt-secret
    namespace: default
```

![image](https://user-images.githubusercontent.com/134774/173197876-531d1a97-70e0-4438-beca-ba07f64ee11c.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): not sure where to find and run this command.
- your Kubernetes cluster version (output of kubectl version):
- 
![image](https://user-images.githubusercontent.com/134774/173197922-33b7e3c0-5c51-4d21-8264-a5b918b15a77.png)

- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
Linux master-ash-1 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
