### ISSUE TITLE
feature request: ingress annotations support ApisixPluginConfig

### ISSUE THREAD

**Issue by dickens7** [apache/apisix-ingress-controller#1086]
### Issue description

Expects to set ApisixService for routes via annotation when Ingress is defined

E.g：
>  k8s.apisix.apache.org/bind-service: myservice
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: apisix
    k8s.apisix.apache.org/use-regex: "true"
    k8s.apisix.apache.org/bind-service: myservice
  name: ingress-v1
spec:
  rules:
  - host: httpbin.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: service1
            port:
              number: 80
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Can you write a detailed proposal? Including its background, and the benefits it can bring. 
Thanks

**Comment by dickens7** [comment]
I thought about it, what I need more should be `ApisixPluginConfig` instead of `ApisixService`

In some simple scenarios that require the use of apisix plugins, it is expected to be able to use Ingress to define routes directly without using ApisixRoute.
The method of Ingress + Annotations is easier for operation and maintenance students to accept and use. At the same time, some management systems also provide visualization functions by reading ingress. Such as zadig.

E.g：

> k8s.apisix.apache.org/plugin-conifg: xxxx

```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixPluginConfig
metadata:
  name: xxxx
spec:
  plugins:
    - name: request-id
      enable: true
```

Use Ingress + Cert-manager(annotations) + ApisixPluginConfig

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpserver-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    k8s.apisix.apache.org/plugin-conifg: xxxx
spec:
  ingressClassName: apisix
  rules:
  - host: local.httpbin.org
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - local.httpbin.org
      secretName: ingress-cert-manager-tls
```

Use ApisixRoute + ApisixPluginConfig + ApisixTls + Certificate

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpserver-tls
spec:
  dnsNames:
    - local.httpbin.org
  issuerRef:
    kind: Issuer
    name: clusterIssuerName
  secretName:  httpserver-tls
  usages:
    - digital signature
    - key encipherment
  renewBefore: 0h55m0s
  duration: 1h0m0s

---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixTls
metadata:
  name: httpserver-tls
spec:
  hosts:
    - local.httpbin.org
  secret:
    name: httpserver-tls

---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: httpserver
spec:
  http:
  - name: httpserver
    match:
      hosts:
        - local.httpbin.org
      paths:
        - /
    backends:
     - serviceName: httpbin
       servicePort: 80
    plugin_config_name: xxxx
```
