### ISSUE TITLE
bug: ApisixRoute v2 version resource is missing status information.

### ISSUE THREAD

**Issue by AlinsRan** [apache/apisix-ingress-controller#1108]
### Issue description

 ApisixRoute v2 version resource is missing `status` field information.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.14.1:dev
- your Kubernetes cluster version (output of kubectl version): 1.24
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): ubuntu 22.04

### Minimal test code / Steps to reproduce

1.  Use ApisixRoute `apisix.apache.org/v2beta3` version
* kubectl apply -f apisixroute.yaml -n $NS

```yaml
# apisixroute.yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
 name: httpbin-route
spec:
 http:
 - name: rule1
   match:
     hosts:
     - httpbin.org
     paths:
       - /ip
   backends:
   - serviceName: httpbin-service-e2e-test
     servicePort: 80
```

* kubectl get ar httpbin-route -o yaml -n $NS
![image](https://user-images.githubusercontent.com/79972061/176082484-766fc541-5800-49cb-8fa7-9a06f6cfcd39.png)

2. Use ApisixRoute `apisix.apache.org/v2` version
* kubectl apply -f apisixroute.yaml -n $NS

```yaml
# apisixroute.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
 name: httpbin-route
spec:
 http:
 - name: rule1
   match:
     hosts:
     - httpbin.org
     paths:
       - /ip
   backends:
   - serviceName: httpbin-service-e2e-test
     servicePort: 80
```

* kubectl get ar httpbin-route -o yaml -n $NS
![image](https://user-images.githubusercontent.com/79972061/176082045-72d3f20c-c98e-4341-a271-8f2379c7a7dd.png)

### Actual result

None.

### Error log

None.
