### ISSUE TITLE
bug: The order of deleting ApisixRoute http and tcp types is wrong

### ISSUE THREAD

**Issue by Horus-K** [apache/apisix-ingress-controller#1122]
### Issue description

First create an ApisixRoute of http,
Then create the ApisixRoute of tcp, both use the same svc,
After the first http ApisixRoute is deleted, the tcp ApisixRoute cannot be used.
At this time, check that apisix upstream has been deleted
Reverse the order of deletion, it will not appear

This won't happen if you use different svc

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4.1
- apisix 2.13.0
- your Kubernetes cluster version (output of kubectl version):  1.20
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

1.create svc
```
apiVersion: v1
kind: Service
metadata:
  name: sentinel-test
  namespace: sentinel
spec:
  ports:
    - name: t1
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: sentinel-test
  type: ClusterIP
  sessionAffinity: None
```
2 create http ApisixRoute 
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: sentinel-test
  namespace: sentinel
spec:
  http:
    - backends:
        - serviceName: sentinel-test
          servicePort: 8080
      match:
        hosts:
          - sentinel.api.xxx.com
        paths:
          - /*
      name: sentinel-test
```
3.create tcp  ApisixRoute 
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: sentinel-test-route
  namespace: sentinel
spec:
  stream:
    - backend:
        serviceName: sentinel-test
        servicePort: 8080
      match:
        ingressPort: 8080
      name: sentinel-test
      protocol: TCP

```
4 now check upstream
![image](https://user-images.githubusercontent.com/48319268/176617244-ff4084bc-3d92-42cd-8e5c-93a259a0d0bf.png)

5 delete http ApisixRoute
check upstream
![image](https://user-images.githubusercontent.com/48319268/176617395-240c2b0c-ee28-46eb-bcbf-4c1f7f855e3d.png)
now the tcp ApisixRoute cannot be used.

### Actual result

The log is normal

### Error log

no

### Expected result

It will not affect other routes after deletion
