### ISSUE TITLE
request help: ApisixRoute binds a apisix service object

### ISSUE THREAD

**Issue by pongpongcn** [apache/apisix-ingress-controller#1173]
### Issue description

We config routes in apisix like this:
```json
{
  "uri": "/*",
  "name": "foo",
  "service_id": "416488338191549120",
  "upstream_id": "416488530257117888"
}
```

In Apisix Ingress way, using ApisixRoute. Defining backends, which refers a k8s service is acceptable. But, it plugins contains too much things. How can I reuse the plugins config set?
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: foo
spec:
  http:
  - name: default
    service_id: "1234567890" # or service_name
    backends:
    - serviceName: foo
      servicePort: 80
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):1.4.1
- your Kubernetes cluster version (output of kubectl version):v1.24.0
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):run in k8s
