### ISSUE TITLE
bug: keyauth header in ApisixRoute CRD doesnt work

### ISSUE THREAD

**Issue by akalittle** [apache/apisix-ingress-controller#1206]
### Issue description

Follow the doc in [ApisixRoute CRD](https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1/ApisixRoute.yaml#L226)

```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: status-tracker
  namespace: launcher
spec:
  http:
    - name: status-tracker-rule
      match:
        hosts:
          - api.xxx.cc
        paths:
          - /status-tracker*
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - ^/status-tracker/(.*)
              - /$1
      backends:
        - serviceName: status-tracker
          servicePort: 8000
      authentication:
        enable: true
        type: keyAuth
        keyAuth:
          header: Authentication

```

### Environment

apache/apisix-ingress-controller:1.4.1

Kubernetes cluster version: 
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.12-gke.2200

### Minimal test code / Steps to reproduce

kubectl apply -f  `the config file`

### Actual result

<img width="415" alt="image" src="https://user-images.githubusercontent.com/38489160/182545240-84350d7a-ce3b-47d0-b570-fcca784442fd.png">

### Error log

no

### Expected result

the keyAuth header need to be  `Authentication`
