### ISSUE TITLE
feature request:  Add plugin support for ApisixConsumer

### ISSUE THREAD

**Issue by akalittle** [apache/apisix-ingress-controller#1214]
### Issue description

[ApisixConsumer CRD](https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1/ApisixConsumer.yaml)

```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixConsumer
metadata:
  name: test-consumer
  namespace: apisix-istio
spec:
  authParameter:
    keyAuth:
      value:
        key: j5giofawfk9OtR6pVvYz
    #  plugins: 
    #    - 
```

Is there a way to bind some plugins to the consumer directly in yaml file ?
However, I know it's possible to apply the plugin via dashboard. But It's more convenient to write all configs in yaml file.

### Environment

Environment
apache/apisix:2.15.0-alpine
apache/apisix-ingress-controller:1.4.1
docker.io/bitnami/etcd:3.5.4-debian-11-r14

Kubernetes cluster version:
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.12-gke.2200
