### ISSUE TITLE
request help: Configure AWS Certifcate on APISIX Ingress

### ISSUE THREAD

**Issue by ochuko3d** [apache/apisix-ingress-controller#1252]
### Issue description

Hi,

I want to use AWS loadbalancer to terminate SSL connections to my cluster, i have gotten a certificate and deployed the ingress controller, which has the certificate listening on port 443. I modified the scheme to HTTPS, but its fails with this "The plain HTTP request was sent to HTTPS port"

Below is my config 

gateway:
```
  type: LoadBalancer
  # If you want to keep the client source IP, you can set this to Local.
  # ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Cluster
   #type: LoadBalancer
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http 
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert-ports: https
     service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*" 
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:127867112076:certificate/25044570-f0a1-4220-ba3c-c88f79731137" 
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
     service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-1-2017-01
  externalIPs: []
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
  tls:
    enabled: true
    servicePort: 443
    containerPort: 9443
    existingCASecret: ""
    certCAFilename: ""
    http2:
      enabled: true
  stream:  # L4 proxy (TCP/UDP)
    enabled: false
    only: false
    tcp: []
    udp: []
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: apisix.local
        paths: []
    tls: []
  #  - secretName: apisix-tls
  #    hosts:
  #      - chart-example.local
```
but it still ends up failing

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): I am not certain, but i got it from the helm chart last night o i guess its the current one
- your Kubernetes cluster version (output of kubectl version): 1.22 - EKS
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): EKS
