### ISSUE TITLE
bug: Restrictions for users(consumers) who are defined in namespaces that include hyphen(-) in their name do not work 

### ISSUE THREAD

**Issue by hesamhamdarsi** [apache/apisix-ingress-controller#1254]
### Current Behavior

let's say we define the "consumer1" in namespace "aaa" . the restriction rules (method, apikey) in apisixRoute CRD  like the following works as expected:
```yml
- name: consumer-restriction
      enable: true
      config:
        allowed_by_methods:
        - user: "aaa_consumer1"
          methods:
          - "GET"

 ```
user is able to send the GET request, but not other methods (as expected)
```sh
GET:
curl https://httpbin.apisix.<DOMAIN>/anything -H 'apikey: <consumer1_key>' -i
HTTP/2 200
Post:
curl https://httpbin.apisix.<DOMAIN>/anything -H 'apikey: <consumer1_key>' -d ' ' -i
HTTP/2 403
```
but as soon as we define the consumer in a namespace like "aaa-bbb" that includes hyphen symbol in it's name, the rule doesn't work as we expect:
```yml
- name: consumer-restriction
      enable: true
      config:
        allowed_by_methods:
        - user: "aaa-bbb_consumer1"
          methods:
          - "GET"

 ```
user has full access on any method:
```sh
GET:
curl https://httpbin.apisix.<DOMAIN>/anything -H 'apikey: <consumer1_key>' -i
HTTP/2 200
Post:
curl https://httpbin.apisix.<DOMAIN>/anything -H 'apikey: <consumer1_key>' -d ' ' -i
HTTP/2 200
```

### Steps to Reproduce

1. Run apisix-ingress-controller using helm chart (chart version: 0.9.3, appVersion: 1.4.1) --> latest version on helm repo
2. create the same consumer once in "aaa" and once in "aaa-bbb" namespaces
3. create a route to httpbin service and enable <consumer-restriction> plugin
4. add restriction rules like allowed_by_methods, whitelist and blacklist for the specific user
5. check the behaviour of consumer in namespace with hyphen include with the other one 

### Environment

- APISIX version : 2.14.1 , Image: 2.15.0-alpine
- Operating system : Linux
- OpenResty / Nginx version : openresty/1.19.9.1

**Comment by tao12345666333** [comment]
please add a test case to cover this one, thanks @AlinsRan   @lingsamuel

**Comment by AlinsRan** [comment]
e2e: https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/suite-plugins/suite-plugins-security/consumer-restriction.go#L215
ns: https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/scaffold/scaffold.go#L38

This scenario has been covered.
In e2e, the default ns format is `ingress-apisix-e2e-tests-xxx-xxx`.

**Comment by tao12345666333** [comment]
@hesamhamdarsi please check the reply 👆

**Comment by hesamhamdarsi** [comment]
Hi again,

The scenario @AlinsRan is shared have a section where all "-" will be replaced by "_" (in apisixConsumer probably because of the tracking consumers to they key, user/pass, etc) and then you injected this automatically in your unit test. 
https://sourcegraph.com/github.com/apache/apisix-ingress-controller@master/-/blob/pkg/types/apisix/v1/types.go?L538#tab=references
So in your unit test, the namespace format is automatically aaa_bbb, while in reality we have to manually specify the namespace.
if you want to have a real test case, I suggest using statically defined namespace in apisixRoute test. 

so instead of this test case:
```yaml
plugins:
   - name: consumer-restriction
     enable: true
     config:
       whitelist:
       - "%s"
```
use this one manually (like in real scenario) and see if it works:
```yaml
plugins:
   - name: consumer-restriction
     enable: true
     config:
       whitelist:
       - ingress-apisix-e2e-tests-xxx-xxx_ jack1
 ```

**Comment by AlinsRan** [comment]
Yeah, the following configurations are actually used in e2e:

```yaml
plugins:
   - name: consumer-restriction
     enable: true
     config:
       whitelist:
       - ingress_apisix_e2e_tests_xxx_xxx_jack1
 ```

In fact, the expectation should be as follows:

```yaml
plugins:
   - name: consumer-restriction
     enable: true
     config:
       whitelist:
       - ingress-apisix-e2e-tests-xxx-xxx_jack1
```
