### ISSUE TITLE
request help: cannot attach domain automatically (external-dns)?

### ISSUE THREAD

**Issue by choryuidentify** [apache/apisix-ingress-controller#1312]
### Issue description

Hi.

I've install APISIX with Ingress controller on GKE Autopilot Cluster.

[External-DNS](https://github.com/kubernetes-sigs/external-dns) is DNS Record updater for assign Public IP to specific sub-domain.
I need automatic assign & update records, but It does not work.

I create Ingress and waiting few minute until appear Ingress's Public IP, but is not appeared.
I think it's the reason of external-dns failure.

I confirmed Ingress functionality via Public IP of LoadBalancer Service.

Ingress YAML
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpserver-ingress
spec:
  ingressClassName: apisix
  rules:
  - host: apisix.dev.test.com # Example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin
            port:
              number: 80
```

Result: Empty Address
```
NAME                 CLASS    HOSTS                     ADDRESS   PORTS   AGE
httpserver-ingress   apisix   apisix.dev.test.com             80      8s
```

It's a design? or I can implement this function by other way? 

Thank you.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
Version: 1.4.1
Git SHA: no-git-module
Go Version: go1.16.15
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64

- your Kubernetes cluster version (output of kubectl version):
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10-gke.600", GitCommit:"2c921d7b040ed9c5a3a1f9407fb109b74d72d0a4", GitTreeState:"clean", BuildDate:"2022-06-02T09:20:24Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
