### ISSUE TITLE
Create apisixupstream resource not showing on dashbord

### ISSUE THREAD

**Issue by hyt05** [apache/apisix-ingress-controller#1321]
### Issue description

This is my config info, after I apply apisix-dashbord upstream doesn't show data
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    component: nginx
spec:
  replicas: 1
  serviceName: nginx
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
        component: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    component: nginx
spec:
  selector:
    component: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: nginx
spec:
  scheme: http
  loadbalancer:
    type: roundrobin
```
kubectl describe apisixupstreams.apisix.apache.org nginx
```
Name:         nginx
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  apisix.apache.org/v2beta3
Kind:         ApisixUpstream
Metadata:
  Creation Timestamp:  2022-09-06T10:52:08Z
  Generation:          1
  Managed Fields:
    API Version:  apisix.apache.org/v2beta3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:loadbalancer:
          .:
          f:type:
        f:scheme:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-09-06T10:52:08Z
  Resource Version:  11980131
  UID:               413f9d7a-bccb-4eef-8183-3ce5c38125c5
Spec:
  Loadbalancer:
    Type:  roundrobin
  Scheme:  http
Events:
  Type    Reason           Age   From           Message
  ----    ------           ----  ----           -------
  Normal  ResourcesSynced  4m5s  ApisixIngress  ApisixIngress synced successfully
```

### Environment

apache/apisix-dashboard:2.13-alpine
apache/apisix:2.13.1-alpine
apache/apisix-ingress-controller:1.4.1
kubernetes：v1.24.2+rke2r1
Linux master1 5.15.0-39-generic #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
