### ISSUE TITLE
bug: unexpected result when ingress restarted

### ISSUE THREAD

**Issue by xiangtianyu** [apache/apisix-ingress-controller#1340]
### Issue description

if we apply yaml quickly just after the ingress restarted, it will cause some unexpected appearance

It occurs when i apply new yaml just after ingress restart, if i restart and wait for a minute, it will handle this case as usual.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.5.0-rc1
- your Kubernetes cluster version (output of kubectl version): 1.24.3
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

I used this yaml to create apisix route:
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: rule3
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backends:
       - serviceName: httpbin
         servicePort: 80
```
and then i restarted apisix ingress and changed this yaml
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backends:
       - serviceName: httpbin
         servicePort: 80
  - name: rule2
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backends:
       - serviceName: httpbin
         servicePort: 80
```

and then apply

### Actual result

it returned like this
<img width="1155" alt="截屏2022-09-19 09 25 33" src="https://user-images.githubusercontent.com/10825900/190937936-f29c1ce5-7227-4244-80ec-bd25a8e7c08b.png">

### Error log

no err log

### Expected result

it should be like this
<img width="1192" alt="截屏2022-09-19 09 16 27" src="https://user-images.githubusercontent.com/10825900/190937952-223f0ac2-b473-40e4-81ae-943c88078d98.png">
