### ISSUE TITLE
request help: Unable to enable Apisix plugins on ingress resource using ApisixPluginConfig

### ISSUE THREAD

**Issue by checkin247** [apache/apisix-ingress-controller#1353]
### Issue description

I have setup apisix on kubernetes and deployed a test pod. I was then following [Annotation guide](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/concepts/annotations.md) to enable plugins on my ingress resources which I deployed using the following yaml:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world2
  namespace: demo
  annotations:
    k8s.apisix.apache.org/plugin-config-name: demo
    k8s.apisix.apache.org/plugin_config_name: demo
    kubernetes.io/ingress.class: apisix
spec:
  rules:
    - host: demo2.k8s.example.com
      http:
        paths:
          - backend:
              service:
                name: hello-kubernetes-hello-world
                port:
                  name: http
            path: /*
            pathType: ImplementationSpecific
---
apiVersion: apisix.apache.org/v2 
kind: ApisixPluginConfig
metadata:
  name: demo
  namespace: ingress-apisix
spec:
  plugins:
  - name: echo
    enable: true
    config:
      before_body: "This is the preface"
      after_body: "This is the epilogue"
      headers:
        X-Foo: v1
        X-Foo2: v2
  - name: response-rewrite
    config:
      headers:
        XXX: tribleX
````

Apisix is setup in the "ingress-apisix" namespace. I believe the "ApisixPluginConfig" should be in the same namespace as noted in here: https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/concepts/annotations.md#use-apisixpluginconfig

> When I access the route, I get the content of the deployed pod however I cannot see any Apisix plugins taking effect. Namely there are no additional response headers.

I took the additional step to use the Apisix Api to overwrite the auto generated routes by the ingress controller to add the plugin configuration. 
This immediately worked but the goal is to use the plugins on the routes defined in the ingress definition.

Appreciate your feedback.

### Environment

- apisix-ingress-controller version: apache/apisix-ingress-controller:1.4.1
- your Kubernetes cluster version (output of kubectl version): v1.21.14
