### ISSUE TITLE
request help: how to configure ingress controller to limit watch ingress resources

### ISSUE THREAD

**Issue by chrecht** [apache/apisix-ingress-controller#1359]
### Issue description

Hello,

How do you limit which kubernetes ingress resources are exposed as apisix route/upstream ?

Currenlty I only want to use the custom CRD to expose a route/upstream in apisix.
I've added appNamspaces and/or namespaceSelector that only those "ingress" resources would be exposed but I think now that this has nothing todo with the sync behavoir from ingress <=> apisix...

Please advice how to limit ingress exposing in apisix.

Thank you
 Christian

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): v2.15.0
- your Kubernetes cluster version (output of kubectl version): v1.20.15
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): ---

apisix, dashboard and ingress are deployed as an helm chart with the following values
        name: apisix-myname
        chart_ref: apisix/apisix
        chart_version: 0.11.1-rc1
        release_namespace: ingress-apisix

```
         apisix:
            replicaCount: 3
          discovery:
            enabled: false
          serviceMonitor:
            enabled: true
          gateway:
            type: LoadBalancer
            externalTrafficPolicy: Local
            loadBalancerIP: 10.1.1.10
            #externalIPs: []
            http:
              enabled: true
              servicePort: 80
              containerPort: 9080
            tls:
              enabled: true
              servicePort: 443
              containerPort: 9443
              existingCASecret: ""
              certCAFilename: ""
              http2:
                enabled: true
              sslProtocols: "TLSv1.2 TLSv1.3"
          admin:
            enabled: true
            credentials:
              admin: SAMPLE588f6d4dfec8d1d597c
              viewer: SAMPLE588f6d4dfec8d1d597c
          ingress-controller:
            enabled: true
            config:
              apisixResourceSyncInterval: "60s"
              apisix:
                serviceName: apisix-myname-admin
                serviceNamespace: ingress-apisix
                servicePort: 9180
                adminKey: "SAMPLE588f6d4dfec8d1d597c"
                clusterName: "default"
              kubernetes:
                ingressClass: "apisix"
                ingressVersion: "networking/v1"
                apisixRouteVersion: "apisix.apache.org/v2"
                appNamespaces: []
                namespaceSelector: [ "apisix.ingress=watching" ]
                resyncInterval: "1m"
                
          dashboard:
            enabled: true
            config:
              conf:
                etcd:
                  endpoints: 
                    - apisix-rtllu-etcd:2379
              authentication:
                users:
                  - username: user
                    password: pass
            ingress:
              enabled: true
              hosts:
              - host: apisix-dashboard.domain.tld
                paths: 
                  - /
```
