### ISSUE TITLE
question: http to https redirecting to wrong port

### ISSUE THREAD

**Issue by checkin247** [apache/apisix-ingress-controller#1422]
### Issue description

Hi,

Using the 'k8s.apisix.apache.org/http-to-https: "true"' redirection from [the example](https://apisix.apache.org/docs/ingress-controller/concepts/annotations/#redirect) doesn't seem to work as expected.
The url http://exmaple.com is redirected to https://example.com:9443 .

### Environment

- version 1.5.0
- kubernetes cluster 1.23.12

### Minimal test code / Steps to reproduce

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    k8s.apisix.apache.org/http-to-https: "true"
  name: ingress-v1
spec:
  ingressClassName: apisix
  rules:
  - host: example.com
    http:
      paths:
      - path: /sample
        pathType: Exact
        backend:
          service:
            name: httpbin
            port:
              number: 80
    tls:
      - hosts:
          - example.com
        secretName: example-tls
````              

### Actual result

redirects to https://example.com:9443

### Error log

not applicable

### Expected result

redirects to https://example.com:
