### ISSUE TITLE
request help:  upgrade 2.14.1 to 2.15 

### ISSUE THREAD

**Issue by wolgod** [apache/apisix-ingress-controller#1435]
### Issue description

If I want to upgrade apisix 2.14.1 to 2.15, can I just use the latest chart and update it? I don't need to change the resources used in my cluster?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Yes

**Comment by anhldbk** [comment]
@wolgod @tao12345666333 Btw, I'm a newbie. I tried to follow [this tutorial](https://apisix.apache.org/docs/ingress-controller/deployments/kind/ ) to setup apisix with kind. 

With a route defined as:

```yaml
# httpbin-route.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backends:
       - serviceName: httpbin
         servicePort: 80
```

I tried multiple times the command below still does not successfully register the route with Apisix.

```sh
kubectl apply -f httpbin-route.yaml
```

I'm using the latest versions of apisix and the ingress controller (apache/apisix:3.1.0-debian). Are the two compatible with each other? I've read the [compatability table](https://apisix.apache.org/docs/ingress-controller/getting-started/#compatibility-with-apisix) and found it may be a cause.
