### ISSUE TITLE
request help:  How to config regex based http request header customization?

### ISSUE THREAD

**Issue by wenhuwang** [apache/apisix-ingress-controller#1444]
### Issue description

I need to match the domain name in the http referer with the v1 string through the ingress configuration, add version: v1 to the http request header, and when the domain name in the referer contains the v2 string, add version: v2 to the http request header.

I have used the proxy-rewrite plugin to achieve statically adding http request headers, I am not sure if it can achieve dynamic complex scenarios, I hava not seen relevant examples.

ask for advice

### Environment

- APISIX version: 2.15.0
- APISIX Ingress Controller version (run /ingress-apisix/apisix-ingress-controller version --long): 
Version: 1.5.0
Git SHA: no-git-module
Go Version: go1.19.2
Building OS/Arch: linux/amd64
- Kubernetes cluster version (output of kubectl version): 
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- OS version (uname -a): CentOS Linux 7 (Core)

**Comment by tao12345666333** [comment]
Can you explain more clearly what are dynamic complex scenarios？

If you want to be very flexible and include logic, maybe a serverless plugin would be a good choice

**Comment by wenhuwang** [comment]
> Can you explain more clearly what are dynamic complex scenarios？
> 
> If you want to be very flexible and include logic, maybe a serverless plugin would be a good choice

For example, Ingress-nginx supports to inject a piece of nginx configuration, as follows:
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: test-ingress
  namespace: demo
  labels:
    app: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: >
      set $headerprefix "";
      if ($http_referer ~* http?://([0-9a-z-]*)(.+)) { set $headerprefix $1; }
      proxy_set_header header01 $headerprefix;
spec:
  ingressClassName: nginx
  rules:
    - host: test.ft.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: servicea
                port:
                  number: 8080
``` 
Is it possible to achieve a similar effect with apisix-ingress?
