### ISSUE TITLE
request help: can I configure Zipkin endpoint globally? 

### ISSUE THREAD

**Issue by mkyc** [apache/apisix-ingress-controller#1521]
### Issue description

I have following definition:

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: echo
  namespace: echo
spec:
  http:
  - name: root
    match:
      hosts:
      - echo.example.com
      paths:
      - "/*"
    backends:
    - serviceName: echo
      servicePort: 8080
    plugins:
      - name: zipkin
        enable: true
        config:
          endpoint: http://tempo.tempo.svc.cluster.local:9411/api/v2/spans
          sample_ratio: 1
```

Is there possibility to configure Zipkin being enabled for all routes with its `endpoint` and `sample_ratio`? Or is it required to define it for each route separately? 

### Environment

- your apisix-ingress-controller version: helm chart 0.10.2
