### ISSUE TITLE
bug:  When deleting ingress, because the service or endpoints do not exist to failed.

### ISSUE THREAD

**Issue by shareinto** [apache/apisix-ingress-controller#1528]
### Issue description

CertManager issues a certificate to create a temporary Ingress and a temporary Pod to verify and provide http101 verification. After the verification, the temporary ingress and pod should be deleted. Since the ingress and the pod are deleted at the same time, the ingress Controller cannot find the endpoint corresponding to the pod when clearing the ingress, so an error is reported and the route clearing fails, which remains in the apisix configuration.
![image](https://user-images.githubusercontent.com/555313/208003988-3157a52c-5a3c-4a5c-8580-dae3ec9892f9.png)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
Version: 1.5.0
Git SHA: https://github.com/apache/apisix-ingress-controller/commit/f23454fa30e92a4e4392a8c5b2b0ffd2d3bf80b4
Go Version: go1.19.2
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
- your Kubernetes cluster version (output of kubectl version):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-eks-a05fdea", GitCommit:"a05fdea9a04815782f9c4b08eed73bb2d78b07e3", GitTreeState:"clean", BuildDate:"2022-06-09T21:50:47Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.19) exceeds the supported minor version skew of +/-1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

### Minimal test code / Steps to reproduce

1. make sure certmanager installed and issuer configed correctly
2. create a ingress with tls like this
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-codefriend-http
    kubernetes.io/ingress.class: apisix
  name: test
  namespace: default
spec:
  rules:
  - host: test.me
    http:
      paths:
      - backend:
          service:
            name: test-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test.me
    secretName: test.me
```
3. remember config dns test.me to the correct ip
4. wait for a few minute ,we will see the temporary route remains in apisix

### Actual result

the temporary route remains in apisix
![image](https://user-images.githubusercontent.com/555313/208005407-7b3b00af-32e7-43cd-998d-3cc28c405924.png)

### Error log

no log provided

**Comment by tao12345666333** [comment]
I haven't reproduced it locally.
Can you provide more information? Maybe it has something to do with your environment? I see you submitted #1529

**Comment by AlinsRan** [comment]
It only takes two steps to reproduce it.

1. ready resource
```yaml
# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-demo-apisix
spec:
  ingressClassName: apisix
  rules:
  - host: httpbin.org
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /headers
        pathType: Prefix
```
2. `kubectl delete svc httpbin`
3. `kubectl delete -f ingress.yaml`
4. result
![image](https://user-images.githubusercontent.com/79972061/208019245-210aa9a3-49c4-4cce-be8f-24e535aa7973.png)

```shell
$ curl http://51.159.206.18/headers  -H 'Host: httpbin.org'
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
</html>
```
