### ISSUE TITLE
feature request: support filter_func for ApisixRoute

### ISSUE THREAD

**Issue by Phoebus888** [apache/apisix-ingress-controller#1532]
### Issue description

我们需要基于 Body 里面某个参数的值来路由，即不同的值要转发到不同的后端 IP:PORT，自带的插件traffic-split只支持header匹配到不同后端

### Environment

apisix-ingress-controller版本为1.5.0
k8s版本为v1.20.6-tke.27

**Comment by Phoebus888** [comment]
配置规则为
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: method-route
  namespace: middle-platform-uat
spec:
  http:
    - name: method
      match:
        filter_func: "function(vars)\n  local core = require ('apisix.core')\n  local body, err = core.request.get_body()\n  if not body then\n      return false\n  end\n\n  local data, err = core.json.decode(body)\n  if not data then\n      return false\n  end\n\n  if data['foo'] == 'bar' then\n      return true\n  end\n\n  return false\nend"
        hosts:
        - test.01lb.vip
        paths:
          - /*
        exprs:
          - subject:
              scope: Header
              name: User-Agent
            op: RegexMatch
            value: ".*dev.*"
      backends:
        - serviceName: mp-outer-gateway
          servicePort: 8080
```
