### ISSUE TITLE
Add new resource ApisixCluster to better support multi clusters

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#160]
Nowdays, we support multi clusters by annotation `k8s.apisix.apache.org/ingress.class`, but it lacks some necessary configurations like authentication.

It would be better if we add a new resource `ApisixCluster`, to define an APISIX cluster.

```yaml
kind: ApisixCluster
metadata:
  name: "qa"
spec:
  serviceName: qa_apisix
  servicePort: 9080
  auth:
      admin_key: xxxxx
```

And we can reference the cluster by add a new field in `ApisixRoute`, `ApisixUpstream` and others.
