### ISSUE TITLE
bug: apply ingress yaml , controller pod got CrashLoopBackOff

### ISSUE THREAD

**Issue by Fabriceli** [apache/apisix-ingress-controller#1659]
### Current Behavior

`kubectl apply -f ingress.yaml`, kubectl got success, but apisix-ingress-controller pod **CrashLoopBackOff**, and I got the ERROR stack:
```sh
2023-02-09T10:56:45+08:00       error   ingress/ingress.go:472  failed to get APISIX gateway external IPs       {"error": "resource name may not be empty"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x17b20cd]

goroutine 496 [running]:
github.com/apache/apisix-ingress-controller/pkg/providers/ingress/translation.(*translator).translateIngressV1(0xc000379530, 0xc000937700, 0x0)
        /build/controller/pkg/providers/ingress/translation/translator.go:147 +0x58d
github.com/apache/apisix-ingress-controller/pkg/providers/ingress/translation.(*translator).TranslateIngress(0xc0009be330?, {0x1f43ce0, 0xc0019c6120}, {0x0?, 0x11?, 0x7?})
        /build/controller/pkg/providers/ingress/translation/translator.go:112 +0x96
github.com/apache/apisix-ingress-controller/pkg/providers/ingress.(*ingressController).sync(0xc000379680, {0x1f424b0, 0xc00059a500}, 0xc000aaa600)
        /build/controller/pkg/providers/ingress/ingress.go:146 +0x49c
github.com/apache/apisix-ingress-controller/pkg/providers/ingress.(*ingressController).runWorker(0xc000379680, {0x1f424b0, 0xc00059a500})
        /build/controller/pkg/providers/ingress/ingress.go:96 +0x4a
created by github.com/apache/apisix-ingress-controller/pkg/providers/ingress.(*ingressController).run
        /build/controller/pkg/providers/ingress/ingress.go:85 +0xda
```

### Expected Behavior

apisix-ingress-controller pod do not CRASH

### Error Logs

```sh
2023-02-09T10:56:45+08:00       error   ingress/ingress.go:472  failed to get APISIX gateway external IPs       {"error": "resource name may not be empty"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x17b20cd]

goroutine 496 [running]:
github.com/apache/apisix-ingress-controller/pkg/providers/ingress/translation.(*translator).translateIngressV1(0xc000379530, 0xc000937700, 0x0)
        /build/controller/pkg/providers/ingress/translation/translator.go:147 +0x58d
github.com/apache/apisix-ingress-controller/pkg/providers/ingress/translation.(*translator).TranslateIngress(0xc0009be330?, {0x1f43ce0, 0xc0019c6120}, {0x0?, 0x11?, 0x7?})
        /build/controller/pkg/providers/ingress/translation/translator.go:112 +0x96
github.com/apache/apisix-ingress-controller/pkg/providers/ingress.(*ingressController).sync(0xc000379680, {0x1f424b0, 0xc00059a500}, 0xc000aaa600)
        /build/controller/pkg/providers/ingress/ingress.go:146 +0x49c
github.com/apache/apisix-ingress-controller/pkg/providers/ingress.(*ingressController).runWorker(0xc000379680, {0x1f424b0, 0xc00059a500})
        /build/controller/pkg/providers/ingress/ingress.go:96 +0x4a
created by github.com/apache/apisix-ingress-controller/pkg/providers/ingress.(*ingressController).run
        /build/controller/pkg/providers/ingress/ingress.go:85 +0xda
```

### Steps to Reproduce

1. execute `kubectl apply -f ingress.yaml`
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "foo.bar.com"
  - http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: service1
            port:
              number: 80
  - host: "*.foo.com"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service2
            port:
              number: 80
```

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
1.6.0
- Kubernetes cluster version (run `kubectl version`)
```sh
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:06Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
```
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)
```sh
Linux metal-master1-sit 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
