### ISSUE TITLE
feat: As a user, I would like a strip-path annotation feature like kong has

### ISSUE THREAD

**Issue by ecoupal-believe** [apache/apisix-ingress-controller#1669]
### Description

I have an ingress that look like that:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    k8s.apisix.apache.org/strip-path: "true"
spec:
  ingressClassName: apisix
  rules:
    - host: api.mycorp
      http:
        paths:
          - path: /api1
            pathType: Prefix
            backend:
              service:
                name: api1
                port:
                  number: 80
          - path: /api2
            pathType: Prefix
            backend:
              service:
                name: api2
                port:
                  number: 80
          - path: /api3
            pathType: Prefix
            backend:
              service:
                name: api3
                port:
                  number: 80
```

I want the upstream path to look like `/test-action?apikey=1234` when I access the following url url: `https://api.mycorp/api2/test-action?apikey=1234`

I already tried with `k8s.apisix.apache.org/rewrite-target-regex` and `k8s.apisix.apache.org/rewrite-target-regex-template` without any success.

**Comment by tao12345666333** [comment]
Sorry for the delay.

So your goal is to rewrite `/$1/$2?apikey=1234` to` /$2?apikey=1234` right?

**Comment by tao12345666333** [comment]
> If set to true, the part of the path specified in the Ingress rule will be stripped out before the request is sent to the service. For example, if the Ingress rule has a path of /foo and the HTTP request that matches the Ingress rule has the path /foo/bar/something, then the request sent to the Kubernetes service will have the path /bar/something.

https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcomstrip-path

**Comment by ecoupal-believe** [comment]
Yes, I actually found a way using proxy-rewrite plugin and/or rewrite-target-regex. This could be an easy feature to work on.

**Comment by dangviettuan** [comment]
@ecoupal-believe Could you please share your configuration on how to apply proxy-rewrite on k8s?

**Comment by ecoupal-believe** [comment]
You can apply something like that:

```
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: my-plugin-config
spec:
  plugins:
  - config:
      regex_uri:
      - ^/[^/?]+/{0,1}(.*)
      - /$1
    enable: true
    name: proxy-rewrite
```

An then attach it to your ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    k8s.apisix.apache.org/plugin-config-name: my-plugin-config
  name: my-ingress
spec:
  ingressClassName: apisix
  rules:
  - http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 80
	path: /my-service
        pathType: Prefix
```
