### ISSUE TITLE
request help: How configuration upstream timeout when use kubernetes ingress resource

### ISSUE THREAD

**Issue by Brhetty** [apache/apisix-ingress-controller#1712]
### Issue description

How configuration upstream timeout when use kubernetes ingress resource 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by sober-wang** [comment]
say [apisix_ingress_docs_health chek](https://apisix.apache.org/docs/ingress-controller/concepts/apisix_upstream/#health-check)

**Comment by ps-19** [comment]
For configuring upstream timeout when use kubernetes ingress resource, you can use the timeout field in the ApisixUpstream resource. 

```
apiVersion: VERSION
kind: ApisixUpstream
metadata:
  name: httpbin
spec:
  timeout:
    connect: 1s // connection timeout
    read: 1s   // read timeout
```

Other method:

`healthCheck` field to configure active health check for your upstream service.

```
apiVersion: 
kind: ApisixUpstream
metadata:
  name: httpbin
spec:
  timeout:
    connect: `s
    read: 1s
  healthCheck:
    active: true
    port: PORT
    interval: 1s
    timeout: 1s

```
