### ISSUE TITLE
request help: How to set plugin priority in ApisixRoute yaml?

### ISSUE THREAD

**Issue by yujinchoi-94** [apache/apisix-ingress-controller#1743]
### Issue description

I have an ApisixRoute which configured with many plugins.
As proxy-rewrite plugin executed first among other plugins, i get modified method in forward-auth. But I want the original method in forward-auth.
Therefore, I'm trying to configure priorities among plugins.

I'm trying to configure plugin priority based on [this](https://apisix.apache.org/docs/apisix/terminology/plugin/#custom-plugin-priority).

However, it seems not working.
Did i configured something wrong?
I've tried adding `plugins[].config._meta.priority` and `plugins[].config.priority`.
Both of them had no effect.

```
k get apisixroute openapi-alimi-route -o yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  ***
spec:
  http:
  - match:
      hosts:
      ***
      paths:
      - ***
    name: rule-alimi-getalimiclflist
    plugins:
    - config:
        _meta:
          priority: 1 # not work
        priority: 1 # not work
        request_headers:
        ***
        request_method: GET
        upstream_headers:
        ***
        uri: ***
      enable: true
      name: forward-auth
    - config:
        disable: false
        prefer_name: true
      enable: true
      name: prometheus
    - config:
        uri: ***
      enable: true
      name: http-logger
    - config:
        headers:
          ***
        uri: ***
      enable: true
      name: proxy-rewrite
    priority: 1
    upstreams:
    - name: cv-upstream
  - match:
      hosts:
      ***
      paths:
      - ***
    name: rule-alimi-alimianswer
    plugins:
    - config:
        _meta:
          priority: 1
        priority: 1
        request_headers:
        ***
        request_method: GET
        upstream_headers:
        ***
        uri: ***
      enable: true
      name: forward-auth
    - config:
        disable: false
        prefer_name: true
      enable: true
      name: prometheus
    - config:
        uri: ***
      enable: true
      name: http-logger
    - config:
        headers:
          ***
        method: GET
        uri: ***
      enable: true
      name: proxy-rewrite
    priority: 1
    upstreams:
    - name: cv-upstream
```

Thank you in advance.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
```
kubectl get deployment dev-apisix-ingress-controller -o=jsonpath='{.spec.template.spec.containers[0].image}' | cut -d ":" -f 2
1.6.0
```
- your Kubernetes cluster version (output of kubectl version):
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-48e63af", GitCommit:"d5258df403235139e634f823608c74f99a29b9c7", GitTreeState:"clean", BuildDate:"2023-01-24T09:32:35Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1
```
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
