### ISSUE TITLE
feat: As a user, I want to completely customize and control the endpoints of this upstream and its corresponding weight through the crd of ApisixUpstream

### ISSUE THREAD

**Issue by ferrisz** [apache/apisix-ingress-controller#1753]
### Description

As a user, I want to completely customize and control the endpoints of this upstream and its corresponding weight through the crd of ApisixUpstream, so that I can implement your own controller to implement service discovery and adjust load balance rate

**Comment by tao12345666333** [comment]
```yaml
# httpbin-upstream.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: httpbin-upstream
spec:
  externalNodes:
  - type: Domain
    name: httpbin.org
```

ApisixUpstream has a `externalNodes` field,  we can add  `externalNodes[].type=IP` or `externalNodes[].type=EndpointIP` 

ref: https://apisix.apache.org/docs/ingress-controller/tutorials/external-service/
