### ISSUE TITLE
request help: How to configure adding headers based on separated traffic?

### ISSUE THREAD

**Issue by Quinlan-Z** [apache/apisix-ingress-controller#1781]
### Issue description

How to configure adding headers based on separated traffic?
How to implement the following configuration in apisix ingress?

```
split_clients "$remote_addr" $helloworld_backend {
    10%   helloworld_grey_server
    *     helloworld_official_server
}

upstream helloworld_official_server{
    server helloworld_official-svc.applet.svc.cluster.local:11001 max_fails=3 fail_timeout=10s weight=100;
    server helloworld_official-svc.applet:11001 max_fails=3 fail_timeout=10s weight=100;
}

upstream helloworld_grey_server{
    server helloworld-grey-svc.applet.svc.cluster.local:12001 max_fails=3 fail_timeout=10s weight=100;
    server helloworld-grey-svc.applet:12001 max_fails=3 fail_timeout=10s weight=100;
}



location /helloworld/v1/ {
    if ($helloworld_backend ~ "helloworld_grey_server") {
        proxy_set_header grey "yes";
    }

    proxy_pass  http://$helloworld_backend/;

}
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.6.0
- your Kubernetes cluster version (output of kubectl version): 1.22.0
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Quinlan-Z** [comment]
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule4
    match:
      hosts:
      - nginx.testapisix.com
      paths:
      - /*
    backends:
     - serviceName: nginx-srv
       servicePort: 80
       weight: 10
       proxy_set_header: (need to add a header here, how to achieve it?)
     - serviceName: nginx-srv1
       servicePort: 80
       weight: 90

**Comment by Quinlan-Z** [comment]
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule4
    match:
      hosts:
      - nginx2.qikqiak.com
      paths:
      - /*
    backends:
     - serviceName: nginx-srv
       servicePort: 80
       weight: 10
       proxy_set_header: (need to add a header here, how to achieve it?)
     - serviceName: nginx-srv1
       servicePort: 80
       weight: 90
```
