### ISSUE TITLE
request help: apisix-ingress-controller  event handling is slow

### ISSUE THREAD

**Issue by jensonfxc** [apache/apisix-ingress-controller#1789]
### Issue Faced

I test that 1000 ApisixRoute resources are created at the same time, and it takes about 10 minutes for all apisix routes to be processed. Check the code and guess that it is caused by using workqueue. Can I adjust the parameters to speed up the processing?

Stable and reproducible after multiple tests

### Environment

1、apisix-ingress-controller version：1.6.0
2、apisix version：2.14
2、Kubernetes cluster version：1.20

### Expected result
ApisixRoute processing time can be faster

### Test yaml
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: test-apisix-xxx
  namespace: test
spec:
  http:
  - name: test-apisix-xxx
    match:
      hosts:
      - test-apisix-xxx.abc.com
      paths:
      - "/*"
    backends:
    - serviceName: test-apisix-xxx
      servicePort: 80
    plugins:
    - name: client-control
      enable: true
      config:
        max_body_size: 20000000
    - name: request-id
      enable: true
      config:
        include_in_response: false
---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: test-apisix-xxx
  namespace: test
spec:
  scheme: http
  retries: 3
  loadbalancer:
    type: roundrobin
  timeout:
    connect: 10s
    read: 60s
    send: 60s
---
apiVersion: v1
kind: Service
metadata:
  name: test-apisix-xxx
  namespace: test
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deploy-type: test
    project-name: test
    deployment-name: test-1
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: test-apisix-xxx
spec:
  hosts:
  - test-apisix-xxx.abc.com
  secret:
    name: cert
    namespace: ingress-cert
```
