### ISSUE TITLE
request help: How to set up global plugin config?

### ISSUE THREAD

**Issue by Fabriceli** [apache/apisix-ingress-controller#1805]
### Issue description

Can we use `ApisixPluginConfig` to set up global plugin? If so, how to config? that fellow config yaml not work well:
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: global-plugin-config
  namespace: apisix
spec:
  plugins:
    - name: skywalking-logger
      enable: true
      config:
        endpoint_addr: "http://skywalking-skywalking-helm-oap.skywalking.svc.cluster.local:12800"
        service_name: "APISIX::APISIX-sit"
        service_instance_name: "APISIX Instance sit"
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
1.6.1
- your Kubernetes cluster version (output of kubectl version):
```sh
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:06Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
```
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
```sh
Linux metal-master1-sit 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ps-19** [comment]
```
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: global-plugin-config
  namespace: apisix
spec:
  plugins:
    - name: skywalking-logger
      enable: true
      config:
        endpoint_addr: "http://skywalking-skywalking-helm-oap.skywalking.svc.cluster.local:12800"
        service_name: "APISIX::APISIX-sit"
        service_instance_name: "APISIX Instance sit"

```


`kubectl apply -f this_file_name.yaml`
