### ISSUE TITLE
bug: apisix-ingress-controller gateway cannot listen tcproute

### ISSUE THREAD

**Issue by zzjin** [apache/apisix-ingress-controller#1816]
### Current Behavior

Apply gateway+tcproute notwork

### Expected Behavior

tcproute works as except.

### Error Logs

```
1 reflector.go:424]  pkg/mod/k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: failed to list *v1alpha2.TCPRoute: tcproutes.gateway.networking.k8s.io is forbidden: User "system:serviceaccount:apisix:apisix-ingress-controller" cannot list resource "tcproutes" in API group "gateway.networking.k8s.io" at the cluster scope
1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: Failed to watch *v1alpha2.TCPRoute: failed to list *v1alpha2.TCPRoute: tcproutes.gateway.networking.k8s.io is forbidden: User "system:serviceaccount:apisix:apisix-ingress-controller" cannot list resource "tcproutes" in API group "gateway.networking.k8s.io" at the cluster scope
```

### Steps to Reproduce

1. Apply k8s gateway api exp version: 
```
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.6.2/standard-install.yaml
```
2. Install apisix with ingress+gateway enabled: 
```bash
helm upgrade -i apisix apisix/apisix -n apisix --create-namespace \
  --set ingress-controller.enabled=true \
  --set ingress-controller.config.apisix.serviceNamespace=apisix \
  --set gateway.type=NodePort \
  --set gateway.http.containerPort=80 \
  --set apisix.kind=DaemonSet \
  --set apisix.hostNetwork=true \
  --set gateway.tls.enabled=true \
  --set gateway.tls.containerPort=443 \
  --set gateway.tls.servicePort=443 \
  --set apisix.securityContext.runAsUser=0 \
  --set ingress-controller.config.kubernetes.enableGatewayAPI=true
```
3. Apply gatewayclass&gateway&tcproute
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: apisix-lb
spec:
  controllerName: apisix.apache.org/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: test-tcp-gateway
spec:
  gatewayClassName: apisix-lb
  listeners:
  - name: test-1
    protocol: TCP
    port: 30001
    allowedRoutes:
      kinds:
      - kind: TCPRoute
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-test-1
spec:
  parentRefs:
  - name: test-tcp-gateway
    sectionName: test-1
  rules:
  - backendRefs:
    - name: pg-cluster-postgresql
      port: 5432
```
### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
```
Version: 1.6.0
Git SHA: no-git-module
Go Version: go1.19.4
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```
- Kubernetes cluster version (run `kubectl version`)
```
clientVersion:
  buildDate: "2023-01-18T19:22:09Z"
  compiler: gc
  gitCommit: ff2c119726cc1f8926fb0585c74b25921e866a28
  gitTreeState: clean
  gitVersion: v1.25.6
  goVersion: go1.19.5
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-01-18T19:15:26Z"
  compiler: gc
  gitCommit: ff2c119726cc1f8926fb0585c74b25921e866a28
  gitTreeState: clean
  gitVersion: v1.25.6
  goVersion: go1.19.5
  major: "1"
  minor: "25"
  platform: linux/amd64
```

- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)

```
Linux master0 5.15.0-1032-gcp #40-Ubuntu SMP Fri Mar 31 01:34:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
