### ISSUE TITLE
request help: route multiple scheme service

### ISSUE THREAD

**Issue by tulequ** [apache/apisix-ingress-controller#1834]
### Issue description

I have a service that listen (one port) on both https and grpcs traffic
How can I route all traffic to another backend with difference scheme (https vs grpcs)?

ApisixUpstream can support only one scheme?

```
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: example
spec:
  scheme: https
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

Thank for help

**Comment by tao12345666333** [comment]
you can try this

```
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name:  server-service
spec:
  portLevelSettings:
    - port: 50051
      scheme: grpc
    - port: 50055
      scheme: https

```
