### ISSUE TITLE
request help: Frequent prompts warn    apisix/upstream.go:69   upstream not found 

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix-ingress-controller#1855]
### Issue description

Why does the Apisix ingress controller frequently request upstream of Apisix, resulting in a large number of 404 requests on my Apisix;

```
2023-06-09T21:24:19+08:00       warn    apisix/upstream.go:69   upstream not found      {"name": "default_js-design-server_3002_service", "url": "http://js-apisix-admin.ingress-apisix.svc.cluster.local:9180/apisix/admin/upstreams/88c42dc3", "cluster": "default"}
2023-06-09T21:24:19+08:00       warn    apisix/upstream.go:69   upstream not found      {"name": "default_js-design-server_50000_service", "url": "http://js-apisix-admin.ingress-apisix.svc.cluster.local:9180/apisix/admin/upstreams/d8c6437f", "cluster": "default"}
```

Steps to Reproduce

```
kubectl apply -f svc.yaml
``` 

``` yaml
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: demo
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - name: http
      port: 3002
      targetPort: 3002
    - name: grpc
      port: 50000
      targetPort: 50000
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: js-design-server
  namespace: js-design-test
spec:
  http:
    - name: serverV1
      # websocket: true
      match:
        paths:
        - /serverV1*
      backends:
      - serviceName: js-design-svc-test
        servicePort: 3002
    - name: server/socket
      websocket: true
      match:
        hosts:
        - ds.js.design
        paths:
        - /*
        - /socket.io*
      backends:
      - serviceName: js-design-svc-test
        servicePort: 50000
---
apiVersion:  apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: js-design-svc-test
  namespace: js-design-test
spec:
  loadbalancer:
    type: roundrobin
  portLevelSettings:
  - port: 50000
    scheme: grpc
  - port: 3002
    scheme: http
```

## As shown in the figure, there are many 404s in the log collection system, which is very unfriendly
![image](https://github.com/apache/apisix-ingress-controller/assets/57084209/c554d0c2-17f6-45bb-9f3f-ce87527651d7)

## Because I have to configure apisixupstream for forwarding on GRPC

@tao12345666333

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.6.1
- your Kubernetes cluster version (output of kubectl version): 1.20
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
