### ISSUE TITLE
request help: How to reference apisiypluginconfigs for ApisixRoute resources

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix-ingress-controller#1862]
### Issue description

Because I want to add complex configurations to Apisixpluginconfigs, ApisixRoute can refer to the name of Apisixpluginconfigs to look like:

https://apisix.apache.org/zh/blog/2022/12/15/how-support-ingress-custom-plugins/#%E6%96%B9%E5%BC%8F%E4%B8%89crd--ingress-annotations-%E6%A8%A1%E5%BC%8F 这样

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Revolyssup** [comment]
You can use http[].plugin_config_name field in ApisixRoute to refer to an existing ApisixPluginConfig.

**Comment by jinjianming** [comment]
> ref to
> 
> https://github.com/apache/apisix-ingress-controller/blob/32c07516b6bf2fe8ff86ecdf65ee04a7afc0c535/test/e2e/suite-plugins/suite-plugins-other/plugin_config.go#L59-L75

How to configure multiple plugins_ Config_ Name, my attempt to configure is invalid
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: buried
spec:
  http:
    - name: buried
      match:
        hosts:
        - a.a.a
        paths:
        - /buried*
      backends:
         - serviceName: 127.0.0.1
           servicePort: 80
      plugin_config_name:
      - clickhouse-logger
      - response-rewrite
```
