### ISSUE TITLE
help request: ApisixUpstream How to assign different ports to different loadbalancer

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix-ingress-controller#1874]
### Description

For the following example, I want 'scheme: grpc' to be a roundrobin and 'scheme: http' to be a hash

```
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: foo
spec:
  loadbalancer:
    type: roundrobin
  portLevelSettings:
  - port: 7000
    scheme: http
  - port: 7001
    scheme: grpc
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
