### ISSUE TITLE
feat: As a user, I want to be able to specify a default SSL cert for ingress controller, so that k8s secret only needs to be created once

### ISSUE THREAD

**Issue by sebschlue** [apache/apisix-ingress-controller#1882]
### Description

It is currently not clear to me if a default ssl cert can be specified.

This can be handy if the ingress controller is reponsible for a subdomain where a wildcard DNS entry and wildcard SSL cert exists, like *.bar.tld

When using regular ingress objects like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
  namespace: foo
spec:
  ingressClassName: apisix
  tls:
  - hosts:
      - foo.bar.tld
    secretName: star-bar-tld-tls
  rules:
  - host: foo.bar.tld
    http:
      paths:
      - backend:
          service:
            name: bar-service
            port:
              number: 80
        path: /
        pathType: Prefix
```

the secret "star-bar-tld-tls" needs to be copied to all required namespaces as cross-namespace-references are not possible with traditional Ingress objects even though the "star" (wildcard) secret is identical in all namespaces.

But if it would be possible to specify a default SSL cert for whole ingress controller, then ingress object could be simplified to 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
  namespace: foo
spec:
  ingressClassName: apisix
  rules:
  - host: foo.bar.tld
    http:
      paths:
      - backend:
          service:
            name: bar-service
            port:
              number: 80
        path: /
        pathType: Prefix
```
and the secret would not need to be copied.

ingress-nginx ingress controller supports this feature, but I did not find it explicitely mentioned in APISIX ingress controller docs, do I guess it is not directly supported.

**Comment by tao12345666333** [comment]
You only want to use Ingress resources instead of CRDs like ApisixRoute, right?

**Comment by sebschlue** [comment]
ApisixRoute works great for me, but I think there is a smiliar thing there: For each ApisixRoute object, a corresponding ApisixTLS object would be needed as well, even though the actual secret could be referenced cross-namespace. 

So, given this example of *.bar.tld with wildcard DNS entry and wildcard SSL certificate, it would be great if I could either:

(a) completely omit creation ApisixTLS objects thus causing apisix ingress controller to just always use the global default SSL cert

(b) create only ONE ApisixTLS what somehow specifies *.bar.tld as hostname, which I believe is not possible today


But of course this is just "nice to have", so just possible enhancement.

**Comment by erSitzt** [comment]
@sebschlue did you find a solution ?
I'm looking at apisix as a replacement for kong and i have a similar problem if i do a 1-to-1 conversion of my setup.
I'm currently using reflector with cert-manager to copy all "default" certificates into all other namespaces where i deploy my workloads and ingresses. sometimes this gets stuck and it feels wrong :)

**Comment by wk-mls** [comment]
In case it's helpful to anyone coming across this thread: I was able to achieve this by deploying an ApisixTls object, with my Ingress objects configured like the simplified one given by sebschlue above: https://apisix.apache.org/docs/ingress-controller/reference/apisix-ingress-controller/api-reference/#apisixtls
```
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: default-tls
  namespace: apisix
spec:
  hosts:
    - "*.example.com"
    - "*.foo.example.com"
    - "*.foo.bar.example.com"
    - "*.example2.com"
  ingressClassName: apisix
  secret:
    name: wildcard-cert
    namespace: apisix
```
Once you've got the ApisixTls object deployed, you should be able to see the SSL configuration through the debug API: https://apisix.apache.org/docs/ingress-controller/reference/apisix-ingress-controller/configuration-troubleshoot/#inspect-translated-adc-configurations

The realization came from seeing this doc on the enterprise site and noticing that ApisixTls objects set the same underlying SSL configurations: https://docs.api7.ai/apisix/how-to-guide/traffic-management/tls-and-mtls/configure-https-between-client-and-apisix/#configure-https-for-apisix

**Comment by AlinsRan** [comment]
@wk-mls's comment above is the correct answer, and it is the recommended way to do this.

No controller-level "default certificate" option is needed: in APISIX the SSL object is
selected by SNI during the TLS handshake, independently of the routes and of the
namespace the route lives in. A certificate declared once therefore applies to Ingresses
in every namespace, and the Secret does not have to be copied around.

So, following @wk-mls: create a single `ApisixTls` with wildcard SNIs, and leave the
`tls` section out of your `Ingress` objects. `spec.secret` takes a name *and* a
namespace, so the Secret only has to exist once.

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: default-tls
  namespace: apisix
spec:
  ingressClassName: apisix
  hosts:
    - "*.bar.tld"
  secret:
    name: star-bar-tld-tls
    namespace: apisix
```

If you are on Gateway API instead, the equivalent is to put the certificate in the
Gateway's `listeners[].tls.certificateRefs` and let HTTPRoutes from other namespaces
attach through `allowedRoutes`.

The one thing not covered is ingress-nginx's `--default-ssl-certificate` acting as a
catch-all for SNIs that match nothing, which is a different feature from what is
described here — `*.bar.tld` is fully covered by a wildcard SNI.

Closing as already resolved. Please reopen if the wildcard `ApisixTls` does not work for
your setup.
