### ISSUE TITLE
help request: How to define keepalive through ApisixUpstream_ The idle of the pool_ Timeout

### ISSUE THREAD

**Issue by sggene** [apache/apisix-ingress-controller#1883]
### Description

```
apiVersion:  apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: nginx
spec:
  loadbalancer:
    type: roundrobin
  keepalive_pool:
    idle_timeout: 90s
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
