### ISSUE TITLE
request help: How to deploy multiple in an environment apisix Ingress Controller + apisix 

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix-ingress-controller#1884]
### Issue description

How to deploy multiple sets like ingress nginx and have a parameter to set up ingress class 

I hope to specify the corresponding ingress apisix when creating an apisixroute, instead of multiple ingress apisixes listening to the same apisixroute

This architecture diagram

![image](https://github.com/apache/apisix-ingress-controller/assets/57084209/15ce8d7e-e77b-4a02-9450-bad207ca670e)

```
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: ingress-test
  namespace: default 
spec: 
  ingressClassName: ccedemo 
```
### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by Fabriceli** [comment]
You need to config ingress-controller kubernetes in helm chart:
- for `private` ingress-controller:
```yaml
ingress-controller:
  enabled: true
  nameOverride: "apisix-ingress-controller-private"
  fullnameOverride: "apisix-ingress-controller-private"
  serviceAccount:
    # -- The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "sa"
  config:
    kubernetes:
      # -- namespace_selector represent basis for selecting managed namespaces.
      # the field is support since version 1.4.0
      # For example, "apisix.ingress=watching", so ingress will watching the namespaces which labels "apisix.ingress=watching"
      namespaceSelector: [ "network=private" ]
      # -- the election id for the controller leader campaign,
      # only the leader will watch and delivery resource changes,
      # other instances (as candidates) stand by.
      electionId: "ingress-apisix-leader-private"
    apisix:
      adminKey: "abcdefghijklmnopqrstuvwsyz1"
      serviceNamespace: apisix-private
      serviceName: apisix-private
```

- for `public` ingress-controller:
```yaml
ingress-controller:
  enabled: true
  config:
    apisix:
      adminKey: "abcdefghijklmnopqrstuvwsyz2"
    kubernetes:
      namespaceSelector: ["network=public"]
```
Reference: [apisix-helm-chart](https://github.com/apache/apisix-helm-chart)
