### ISSUE TITLE
Disable consumer name in Prometheus metrics (because it blows up with high cardinality

### ISSUE THREAD

**Issue by frankkoornstra** [apache/apisix-ingress-controller#1904]
### Description

I love that Protmetheus has such good support in Apisix, it really contributes to the observability. The only thing I wish for is to be able to disable the `consumer` label. Prometheus isn't great with high cardinality labels and consumer is one of those. We're not really interested in the consumer anyway - we log the requests another way - but we _are_ interested in the metrics without that level of detail. A simple `disable_consumer_name: true` in the settings would do the trick :pray:

**Comment by tao12345666333** [comment]
Do you want to disable it globally, or a prometheus plugin on a certain route?

**Comment by frankkoornstra** [comment]
For my use case, on the plugin on the route. Globally would be nice but I'd rather have more granular options

**Comment by acuteaura** [comment]
you should be able to do this inside prometheus with

```
writeRelabelConfigs:
- action: labeldrop
  regex: consumer
```

in Prometheus Operator, most CRDs should also have a `relabelings` key that takes the same format.

**Comment by frankkoornstra** [comment]
Thanks for the tip. I'm deploying Apisix through the official Helm chart however and I don't think it has any facilities for this. Only thing I can find is this:
```yaml
# -- Observability configuration.
metrics:
  serviceMonitor:
    # -- Enable or disable Apache APISIX serviceMonitor
    enabled: false
    # -- namespace where the serviceMonitor is deployed, by default, it is the same as the namespace of the apisix
    namespace: ""
    # -- name of the serviceMonitor, by default, it is the same as the apisix fullname
    name: ""
    # -- interval at which metrics should be scraped
    interval: 15s
    # -- @param serviceMonitor.labels ServiceMonitor extra labels
    labels: {}
    # -- @param serviceMonitor.annotations ServiceMonitor annotations
    annotations: {}
```

Maybe I can create my own ServiceMonitor instead and do some relabeling.
