### ISSUE TITLE
Support for HTTPS backends

### ISSUE THREAD

**Issue by sebschlue** [apache/apisix-ingress-controller#1905]
### Description

Apache APISIX Ingress Controller does not seem to have support for HTTPS backends.

I noticed this when I wanted to expose Vault Web-UI via Ingress.

Other ingress controllers support this feature out-of-the-box but for APISIX ingress controller, I did not find a way to configure this.

Places I looked at:

https://apisix.apache.org/docs/ingress-controller/references/apisix_route_v2/

https://apisix.apache.org/docs/ingress-controller/concepts/apisix_route/

I also did some googeling and found this:

https://github.com/apache/apisix/discussions/6771

But this is unanswered as of today.

I think this is a very important feature and in case APISIX ingress controller actually does not support it yet, I would like to request this feature :)

**Comment by tao12345666333** [comment]
In fact, we have had this feature for a long time. Through the ApisixUpstream resource, you can set the schema of upstream/backends to support http/https/grpc/grpcs and more.

ref: 
https://github.com/apache/apisix-ingress-controller/blob/e809cfbaaad6f6c3cbd23f5ec8e93bc1d87f543d/test/e2e/suite-features/scheme.go#L138

**Comment by sebschlue** [comment]
Ah, thank you very much :) 

This works for me now:

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: vault
  namespace: svc-vault
spec:
  http:
  - name: vault
    match:
      hosts:
      - vault.${DOMAIN}
      paths:
      - /*
    backends:
       - serviceName: vault-active
         servicePort: 8200
---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: vault-active
  namespace: svc-vault
spec:
  scheme: https
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: vault
  namespace: svc-vault
spec:
  hosts:
  - vault.${DOMAIN}
  secret:
    name: vault-ssl-cert
    namespace: ingress-apisix
```
