### ISSUE TITLE
bug: Apisix keeps throwing "warn  apisix/upstream.go:69  upstream not found"

### ISSUE THREAD

**Issue by adriano-brito-ts** [apache/apisix-ingress-controller#1926]
### Current Behavior

APISIX Ingress controller keeps throwing these warns:

`warn    apisix/upstream.go:69    upstream not found    {"name": "dev_echo-service_10052_service", "url": "http://apisix-admin.apisix-ingress.svc.cluster.local:9180/apisix/admin/upstreams/f0b15d95", "cluster": "default"}`

I created a route and upstream and they seem like this:

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: echo-service
  namespace: dev
spec:
  http:
  - name: default-route
    match:
      hosts:
      - echo.home.lab
      paths:
      - "/echo/*"
    backends:
    - serviceName: echo-service
      servicePort: 10052
    plugins:
    - name: redirect
      enable: true
      config: 
        http_to_https: true
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/echo(/|$)(.*)", "/$2"]
---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: echo-service
  namespace: dev
spec:
  loadbalancer:
    type: least_conn
  healthCheck:
    active:
      type: http
      httpPath: "/v1/status"
      timeout: 5
      healthy:
        successes: 3
        interval: 2s
        httpCodes:
          - 200
          - 206
```

When I delete the resources, it now keeps throwing additional warn messages like these:

```
apisix-ingress-controller-8dd7c7474-tk62l 2023-08-15T00:22:42+08:00    warn    apisix/upstream.go:69    upstream not found    {"name": "dev_echo-service_10052", "url": "http://apisix-admin.apisix-ingress.svc.cluster.local:9180/apisix/admin/upstreams/7b294759", "cluster": "default"}

apisix-ingress-controller-8dd7c7474-tk62l 2023-08-15T00:22:42+08:00    warn    apisix/upstream.go:69    upstream not found    {"name": "dev_echo-service_10052_service", "url": "http://apisix-admin.apisix-ingress.svc.cluster.local:9180/apisix/admin/upstreams/f0b15d95", "cluster": "default"}

apisix-ingress-controller-8dd7c7474-tk62l 2023-08-15T00:22:42+08:00    warn    apisix/apisix_upstream.go:526    sync ApisixUpstream failed, will retry    {"object": {"Type":3,"Object":{"Key":"dev/echo-service","OldObject":null,"GroupVersion":"apisix.apache.org/v2"},"OldObject":null,"Tombstone":{}}, "error": "apisixupstream.apisix.apache.org \"echo-service\" not found"}
```

### Expected Behavior

I expect these warning not appear as the route and upstream works fine and seems correctly bounded. And it's weird it keeps saying that about already deleted resources. Is there any event delete cache? Is there a way to flush it?

### Error Logs

```
apisix-ingress-controller-8dd7c7474-tk62l 2023-08-15T00:22:42+08:00    warn    apisix/upstream.go:69    upstream not found    {"name": "dev_echo-service_10052", "url": "http://apisix-admin.apisix-ingress.svc.cluster.local:9180/apisix/admin/upstreams/7b294759", "cluster": "default"}

apisix-ingress-controller-8dd7c7474-tk62l 2023-08-15T00:22:42+08:00    warn    apisix/upstream.go:69    upstream not found    {"name": "dev_echo-service_10052_service", "url": "http://apisix-admin.apisix-ingress.svc.cluster.local:9180/apisix/admin/upstreams/f0b15d95", "cluster": "default"}

apisix-ingress-controller-8dd7c7474-tk62l 2023-08-15T00:22:42+08:00    warn    apisix/apisix_upstream.go:526    sync ApisixUpstream failed, will retry    {"object": {"Type":3,"Object":{"Key":"dev/echo-service","OldObject":null,"GroupVersion":"apisix.apache.org/v2"},"OldObject":null,"Tombstone":{}}, "error": "apisixupstream.apisix.apache.org \"echo-service\" not found"}
```

### Steps to Reproduce

1. Installed APISIX with Manifest generated with helm
2. Created route and upstream with ApisixRoute and ApisixUpstream resources
3. Watch apisix ingress controller logs

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)

```
Version: 1.6.1
Git SHA: no-git-module
Go Version: go1.19.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```

- Kubernetes cluster version (run `kubectl version`)

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)

N/A
