### ISSUE TITLE
request help: how to use wildcards in paths with ApisixRoute CRD

### ISSUE THREAD

**Issue by machadojoao** [apache/apisix-ingress-controller#1927]
### Issue description

Hi, I have some APIs paths like:

/api/:id/my-entity1
/api/:id/my-entity2

I could not use the CRD ApisixRoute because it has a validation for this field that the wildcard must be at the end.

` spec.http[0].match.paths[0] in body should match '^/[a-zA-Z0-9\-._~%!$&'()+,;=:@/]*\*?$'`

But if I use the admin api directly (our by the dashboard), I'm able to use a wildcard at path like:

`{
  "uris": [
    "/api/*/my-entity1",
    "/api/*/my-entity2"
  ],
  "name": "route,
  "priority": 0,
  "methods": [
    "GET"
  ],
  "upstream_id": "2fa86803"
  "status": 1
}`

Is there anyway to do this with CRDs?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Good catch!

I think we can change the rules.

**Comment by xtha** [comment]
`The ApisixRoute "ar-iot-node" is invalid: spec.http.match.paths: Invalid value: "/assets/help/*/rulenode/*": spec.http.match.paths in body should match '^/[a-zA-Z0-9\-._~%!$&'()+,;=:@/]*\*?$'`

**Comment by byblakeorriver** [comment]
I hit the same issue.

**Comment by pottekkat** [comment]
As a workaround, you can use regular expression matching. For example:

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: speaker-topics-route
spec:
  http:
    - name: speaker-topics
      match:
        hosts:
          - conferenceapi.azurewebsites.net
        paths:
          - /*
        exprs:
          - subject:
              scope: Path
              name: topics
            op: RegexMatch
            value: "^/speaker/[^/]*/topics$"
        methods:
          - "GET"
      upstreams:
        - name: conference-api-upstream
```

See [navendu.me/posts/batching-requests](https://navendu.me/posts/batching-requests/#configure-routes) for full explanation.

Should we still change the rule or continue with this workaround?
