### ISSUE TITLE
help request: Invalid FORWARDED_PORT header

### ISSUE THREAD

**Issue by JoniJnm** [apache/apisix-ingress-controller#1948]
### Description

Hi,

I'm using apisix and I have a problem with the header `FORWARDED_PORT`.

* The original request is: `GET https://my.host` (port 443)
* There is a `ApisixTls`
* There is a `ApisixRoute` pointing to a specific service at port 80 (internally 8080)
* [Apisix internally uses the port 9443](https://github.com/apache/apisix-helm-chart/blob/5d6dfbe512583816a8380619174e1df844f6965e/charts/apisix/values.yaml#L278)

The request header sent to my internal service is:
* FORWARDED_PROTO: https (ok)
* FORWARDED_HOST: my.host (ok)
* FORWARDED_PORT: 9443 (this should be the original 443, not the internally 9443 apisix port)

Using ingress instead of apisix is ok on my app. Do I need to add some configuration or plugin to propagate the right port?

I'm not sure if the issue should be a bug or support.

### Environment

- APISIX version (run `apisix version`): 3.4.1  ([apisix helm chart 1.5.1](https://artifacthub.io/packages/helm/apisix/apisix/1.5.1))
- Operating system (run `uname -a`): ubuntu 22.04
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1

**Comment by Revolyssup** [comment]
@JoniJnm Please also provide your Ingress as well as ApisixRoute configuration

**Comment by JoniJnm** [comment]
Due it's the same problem with http and is more easy to replicate, I paste the config without tls.

Just the header `FORWARDED_HOST` with http is `9080` with apisix and 80 with ingress.

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: my-apisix
spec:
  http:
    - name: my-api
      match:
        hosts:
          - my.host
        paths:
          - /*
      backends:
        - serviceName: my-service
          servicePort: 80
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: my.host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80
```
