### ISSUE TITLE
bug: There does not seem to be ANY connection between a ApisixRoute object and a ApisixConsumer object

### ISSUE THREAD

**Issue by sebschlue** [apache/apisix-ingress-controller#1950]
### Current Behavior

You can specify authentication type inside a ApisixRoute object, but even though there can be more than one ApisixConsumer for the same authentication type in the same namespace, you cannot specify which ApisixConsumer should be connected with which ApisixRoute.

This effectively means that you can only configure ONE type of authentication for the whole namespace.

So, for example:

Given that you have three microservices running in some namespace:

You can configure:
- one to use basic auth
- one to use key auth
- one to use jwt auth

You can also configure:
- all three to use jwt auth with the same key

But you cannot configure:
- all three to use jwt auth but with different keys.

### Expected Behavior

There needs to be a way to connect ApisixRoute object to ApisixConsumer object, for instance by being able to specify the NAME of the consumer object from inside the ApisixRoute object.

### Steps to Reproduce

Follow the tutorial: https://apisix.apache.org/docs/ingress-controller/tutorials/enable-authentication-and-restriction/

and try to configure JWT auth for more than one microservice in the same namespace, so that each microservice uses a different JWT key.

### Environment

k8s: AWS EKS v1.24.13

ingress-controller: container image:  apache/apisix-ingress-controller:1.6.0

**Comment by tao12345666333** [comment]
Thanks [Aurelia](https://github.com/acuteaura)

**Comment by sebschlue** [comment]
Thank you very much for your reply. 

Unfortunately, this does not work for me.

If I understand this correctly, then "jack1" is the name of the consumer object and "default" is the name of the namespace.

I have now tried to get this working with a simple example of the standard kubernetes dashboard deployed in "kubernetes-dashboard" namespace:


```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  http:
  - authentication:
      enable: true
      type: basicAuth
    backends:
    - serviceName: kubernetes-dashboard
      servicePort: 443
    match:
      hosts:
      - XXX
      paths:
      - /*
    name: rule
    plugins:
    - name: redirect
      enable: true
      config:
        http_to_https: true
    - name: ip-restriction
      enable: true
      config:
        whitelist:
        - XXX
    - name: consumer-restriction
      enable: true
      config:
        whitelist:
        - kubernetes-dashboard_kubernetes-dashboard-basic-auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixConsumer
metadata:
  name: kubernetes-dashboard-basic-auth
  namespace: kubernetes-dashboard
spec:
  authParameter:
    basicAuth:
      secretRef:
        name: kubernets-dashboard-basic-auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  hosts:
  - XXX
  secret:
    name: XXX
    namespace: ingress-apisix
---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  scheme: https
``` 

Basic Auth works, so if I disable consumer-restriction, everything is fine.

But once I enable consumer-restriction, I get error message

```
{"message":"The consumer_name is forbidden."}
```
