### ISSUE TITLE
request help: When i create a Ingress,  Why is an empty certificate generated?

### ISSUE THREAD

**Issue by jelly320** [apache/apisix-ingress-controller#2002]
### Issue description

In our business scenario， we have our own server certificate request。

I create a secret，
```
kubectl create secret tls 996a-tls   --cert=996a.com.crt  --key=996a.com.key
```
and then I create an ingress, use this secret,
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testservice-ingress
spec:
  # apisix-ingress-controller is only interested in Ingress
  # resources with the matched ingressClass name, in our case,
  # it's apisix.
  ingressClassName: apisix
  rules:
  - host: test-serivce-ingress.996a.com
    http:
      paths:
      - backend:
          service:
            name: test-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test-serivce-ingress.996a.com
    secretName: 996a-tls
```

Everything is ok：
![image](https://github.com/apache/apisix-ingress-controller/assets/12443489/cae39c37-de32-40b4-9abf-57f50b767c6d)

but why is an empty certificate generated?
![image](https://github.com/apache/apisix-ingress-controller/assets/12443489/1ef2cffe-bde9-4ac5-a6ad-a7af01114267)

This caused my https request to not respond properly：
```
# curl https://test-serivce-ingress.996a.com:9443
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

# curl http://test-serivce-ingress.996a.com:80
test-clusterip-deploy-dfdbbddfd-h9m2f
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

apisix verson:  apache/apisix:3.5.0-debian

apisix-ingress-controller version: apache/apisix-ingress-controller:1.6.0

kubenetes version: v1.24.6
