### ISSUE TITLE
request help: Redirect HTTP to HTTPS doesn't use the configured port

### ISSUE THREAD

**Issue by ventaubain** [apache/apisix-ingress-controller#2027]
### Issue description

I have an Apisix deployment in a K8S cluster by Helm chart (version 1.7.1). I want use the redirect plugin to redirect http to https on port 32443 but the redirection is to 9443. I follow the advices from #1082 

Apisix values.yaml

```
gateway:
  type: NodePort
  tls:
    enabled: true
    nodePort: 32443
    containerPort: 32443
  http:
    nodePort: 32080
pluginAttrs:
  redirect:
    https_port: 32443
```

ApisixRoute config

```
    plugins:
      - name: redirect
        enable: true
        config:
          http_to_https: true
```

where is my mistake ?

### Environment

- APISIX version (run `apisix version`): chart: apisix-1.7.1, version: 3.6.0
