### ISSUE TITLE
request help:  How to import rule set files in Coraza waf 

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix-ingress-controller#2044]
### Issue description

see: https://github.com/apache/apisix-ingress-controller/issues/2043

I know the configuration method for a ruleset, but if multiple rulesets are referenced? Or is it possible to import files to make the firewall plugin effective? Configuration by configuration is too cumbersome.

 This is the ruleset  https://github.com/coreruleset/coreruleset/tree/v4.0/dev/rules

**Comment by kayx23** [comment]
Try `Include @owasp_crs/*.conf`

**Comment by DokiDoki1103** [comment]
Do you have a detailed tutorial? Or a complete example

**Comment by DokiDoki1103** [comment]
> Try `Include @owasp_crs/*.conf`

Hello sister, can you provide a complete demo? Also, which folder should these confs be placed in?

**Comment by kayx23** [comment]
APISIX uses [coraza-proxy-wasm](https://github.com/corazawaf/coraza-proxy-wasm/tree/main), in which I found:

![image](https://github.com/apache/apisix-ingress-controller/assets/39619599/4da5074c-ffa5-4eab-8f67-5df6cfae659e)

I have not tested this myself but I imagine updating configs here would serve the purpose:

![image](https://github.com/apache/apisix-ingress-controller/assets/39619599/4b04f8fb-675e-4ca2-97ce-55e918f4cb2c)

Let me know if this works.

**Comment by kayx23** [comment]
cc: @sn0rt @huanli-meng

**Comment by DokiDoki1103** [comment]
Elder sister means that I need to import the firewall rules into a folder in apixsix, and then configure them directly like this?

```
curl -i http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '{
  "uri": "/anything",
  "plugins": {
    "coraza-filter": {
      "conf": {
        "directives_map": {
          "default": [
            "SecDebugLogLevel 9",
            "SecRuleEngine On",
            "SecRule Include @owasp_crs/xxxx/xx.conf"
          ]
        },
        "default_directives": "default"
      }
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```

**Comment by kayx23** [comment]
The CRS should come embedded with the wasm module and you should not need to worry about the path.

The path is internal, [owasp_crs gets mapped to crs](https://github.com/corazawaf/coraza-proxy-wasm/blob/c62a359c29d736892ca09527a353410b13963c9e/wasmplugin/fs.go#L31) so `owasp_crs/*.conf` correspond to these files that end with `.conf`: https://github.com/corazawaf/coraza-proxy-wasm/tree/main/wasmplugin/rules/crs

So I'd suggest you try this:

```
  "plugins": {
    "coraza-filter": {
      "conf": {
        "directives_map": {
          "default": [
            "SecDebugLogLevel 9",
            "SecRuleEngine On",
            "Include @crs-setup-demo-conf",
            "Include @owasp_crs/*.conf"
          ]
        },
        "default_directives": "default"
      }
    }
  }
```

**Comment by DokiDoki1103** [comment]
Dear sister, I still need your help
 
  I configured yaml to enable firewall plugin support for a certain route, but it reported an error 
  
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: route-ip
    plugins:
    - name: coraza-filter
      enable: true
      config:
        default_directives: "default"
        directives_map:
          defalut: 
          - "SecDebugLogLevel 9"
          - "SecRuleEngine On"
          - "Include @crs-setup-demo-conf"
          - "Include @owasp_crs/*.conf"
    match:
      hosts:
      - test.lyck6.cn
      paths:
      - "/ip"
    upstreams:
    - name: httpbin-upstream
```

 The error is because the plugin was not found 

```
Events:
  Type     Reason               Age                   From           Message
  ----     ------               ----                  ----           -------
  Warning  ResourceSyncAborted  25s (x51 over 5m30s)  ApisixIngress  ApisixIngress synced failed, with error: 1 error occurred:
           * unknown plugin [coraza-filter]
```


Then I will configure configMap to support plugins, which is the document I referenced


https://apisix.apache.org/blog/2023/09/08/APISIX-integrates-with-Coraza/

<img width="639" alt="图片" src="https://github.com/apache/apisix-ingress-controller/assets/62740231/5c6756d1-ff4d-4fd6-9167-56b457079ace">

There is a path that I don't know what I should fill in


```/Home/ubuntu/coraza proxy wasm/build/main.wasm```



The path I write by default does not work, do I still have any configuration errors?
