### ISSUE TITLE
feat: Add support for non auth plugins with ApisixConsumer

### ISSUE THREAD

**Issue by 223311** [apache/apisix-ingress-controller#2069]
### Description

Hey Team,

I'm looking to set up a consumer group via CRD, but I'm having trouble finding the specific CRD for that. Additionally, I've created the consumer using the YAML below. How can I incorporate a plugin into this consumer?

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixConsumer
metadata:
  name: abc
spec:
  authParameter:
    keyAuth:
      value:
        key: "abc12345"
```

Any guidance on adding a plugin to this consumer would be appreciated!
