### ISSUE TITLE
request help: How to use the public API to expose the Prometheus plugin?

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix-ingress-controller#2100]
### Issue description

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  namespace: itihey-system
  name: apisix-monitor
spec:
  plugins:
    - name: prometheus
      enable: true
      config:
        prefer_name: true
    - name: public-api
      enable: true
      config:
        uri: /apisix/prometheus/metrics
```
 After configuring as above, all of my routes returned a 404 error 

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
3.7.0
