### ISSUE TITLE
request help: large file upload  not  work

### ISSUE THREAD

**Issue by RedBlackWolf** [apache/apisix-ingress-controller#2160]
### Issue description

I configured an apisixroute and connected it to the apache service with backends 
Normal operation is fine, but it does not work normally when uploading large files (> 2GB).   
It looks like timeout and it's weird. Applying request_buffering: false to the proxy-control to plugin will cause more errors. Is there a solution?

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: route
spec:
  http:
  - name: route-upload
    match:
      hosts:
      - aaa.com
      paths:
      - /upload/*
    upstreams:
    - name: web-upload
    timeout:
      connect: "8h"
      send: "8h"
      read: "8h"
    plugins:
    - name: proxy-control
      enable: true
      config:
        request_buffering: false
```

### Environment

- apisix ingress-controller 1.8.0
- kubectl 1.28.2 (output of kubectl version):
- Rocky Linux release 8.8
