### ISSUE TITLE
request help: how to set plugin priorities

### ISSUE THREAD

**Issue by rhysxevans** [apache/apisix-ingress-controller#2191]
### Description

Hi, as a user I would like to use the `ApisixRoute` api to set the plugin priorities as per https://docs.api7.ai/apisix/reference/plugin-common-configurations#_metapriority , this should probably include via the `ApisixPluginConfig` api

Any help is appreciated

**Comment by kayx23** [comment]
Can you try something like this:

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
    - name: httpbin-route
      match:
        paths:
          - /ip
      backends:
        - serviceName: httpbin
          servicePort: 80
      plugins:
      - name: limit-count
        enable: true
        config:
          _meta:
            priority: 1200
          time_window: 10
          count: 2
          rejected_code: 429
```

and check in the apisx pod if the `_meta.proprity` is updated? You can port forward 9180 and  `curl "http://127.0.0.1:9180/apisix/admin/routes" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`.
