### ISSUE TITLE
request help: how to translate the nginx weight-based annotation to apisix ingress controller

### ISSUE THREAD

**Issue by ruiruijianggg** [apache/apisix-ingress-controller#2199]
### Issue description

I want to know how to translate the weight-based canary annotation in nginx【nginx.ingress.kubernetes.io/canary-weight】. The apisix ingress controller implements the canary function based on the traffix-split plug-in. Now I can only get the weight of the gray upstream from annotation. And the traffic-split plugin-in needs the id and weight of both the baseline upstream and the gray upstream. How the apisix ingress controller implement canary publishing based annotations?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.8.0
- your Kubernetes cluster version (output of kubectl version): v1.25.3
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by pottekkat** [comment]
@ruiruijianggg From the [Nginx Ingress Controller docs](https://kubernetes.github.io/ingress-nginx/examples/canary/#create-ingress-pointing-to-your-canary-deployment) it seems like the weight you set in the `nginx.ingress.kubernetes.io/canary-weight` is the the percentage of traffic you want to route to your canary deployment. In APISIX, the you can configure a more granular traffic split where you can specify the ratio of how traffic is to be split between your baseline deployment and canary deployment. So if you want to directly translate, you can translate the percentage to ratio.

`nginx.ingress.kubernetes.io/canary-weight: 50` would mean 50% to canary release. In `ApisixRoute`, this becomes:

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: canary-release
spec:
  http:
    - name: canary-route
      match:
        paths:
          - /*
      backends:
        - serviceName: baseline-deployment
          servicePort: 8080
          weight: 50
        - serviceName: canary-deployment
          servicePort: 8080
          weight: 50
```

The weight can also be 1:1 or 2:2 as it would be treated as ratios as opposed to percentages in the Nginx annotation.
