### ISSUE TITLE
配置k8s apisix ingress grpc的协议不生效，请帮助我

### ISSUE THREAD

**Issue by olddriver4** [apache/apisix-ingress-controller#2207]
### Description

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-grpc
  namespace: app
  annotations:
    kubernetes.io/ingress.class: apisix
    k8s.apisix.apache.org/upstream-scheme: grpc
spec:
  rules:
    - host: "base-grpc.app.ntrnl"
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: base
                port:
                  name: grpc
```

<img width="857" alt="image" src="https://github.com/apache/apisix/assets/28889568/20aa3fc8-fa47-45aa-aa91-f6fdbd05238a">      

`grpcurl -plaintext base-grpc.app.ntrnl:80 list social.base.PortalService`    
我确认是生效的，报错如下：       
`Failed to list methods for service "social.base.PortalService": rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: protocol error`   

我的域名做了host解析，LB使用的是4层TCP协议，想问问这个问题出在哪里，我找了网上的配置都不能解决！   
服务绝对没有问题，因为我使用svc host访问是正确的！    

### Environment

- APISIX version (run `apisix version`): 3.7
