### ISSUE TITLE
request help: create stream route to proxy to TLS over TCP upstream

### ISSUE THREAD

**Issue by joshdcu** [apache/apisix-ingress-controller#2254]
### Issue description

The requirement:
- My use case is already documented and supported by APISIX [here](https://apisix.apache.org/docs/apisix/stream-proxy/#proxy-to-tls-over-tcp-upstream).
- I am aware that proxying to TLS over TCP upstream requires rebuilding APISIX and I have already done this.
- I am able to achieve my use case by making suitable requests to the admin API but this is done manually and not declaratively as can be done with the ingress controller.

The problem:
- I am unable to create suitable `ApisixRoute` and `ApisixUpstream` resources that instruct the APISIX ingress controller to create a stream route to proxy to TLS over TCP upstream.

The ask:
- Looking at the `ApisixRoute` and `ApisixUpstream` CRDs, none of them defines a `tcp` or `tls` scheme. Is this something that is currently supported by the APISIX ingress controller?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
```
Version: 1.8.2
Git SHA: 57b5aee
Go Version: go1.21.11
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```
- your Kubernetes cluster version (output of kubectl version):
```
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.1+rke2r1", GitCommit:"6911225c3f747e1cd9d109c305436d08b668f086", GitTreeState:"clean", BuildDate:"2024-05-15T15:44:16Z", GoVersion:"go1.22.2 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): N/A

**Comment by sereneshikari** [comment]
You're right, @vicaya 😞 The custom resources do not provide feature parity with the APISIX API. I understand it might be challenging but I guess this is important given the [composite architecture the APISIX team is introducing](https://apisix.apache.org/docs/ingress-controller/composite/) which relies solely on the APISIX custom resources

**Comment by sereneshikari** [comment]
I think this issue is still relevant 😢

**Comment by sereneshikari** [comment]
I think this issue is still relevant 😢

**Comment by joshdcu** [comment]
I think this issue is still relevant 😢

**Comment by joshdcu** [comment]
I think this issue is still relevant 😢

**Comment by joshdcu** [comment]
Understood, thanks for the clarification! Let's keep this issue open till this feature is supported 👍

**Comment by joshdcu** [comment]
I think this issue is still relevant 😢

**Comment by joshdcu** [comment]
I think this issue is still relevant 😢

**Comment by AlinsRan** [comment]
This should be possible as of 2.2.0.

Both `ApisixUpstream.spec.scheme` and `BackendTrafficPolicy.spec.scheme` used to be restricted to the L7 set (`http`, `https`, `grpc`, `grpcs`), so there was no way to express a TLS upstream on a stream route even though APISIX itself accepts `tls`. #2830 relaxed that validation, and `tcp`, `tls` and `udp` are now accepted.

For an `ApisixRoute` stream rule the scheme comes from an `ApisixUpstream` named after the backend Service:

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: nginx          # must match the Service name below
spec:
  ingressClassName: apisix
  scheme: tls
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: nginx-tcp-route
spec:
  ingressClassName: apisix
  stream:
    - name: rule1
      protocol: TCP
      match:
        ingressPort: 9100
      backend:
        serviceName: nginx
        servicePort: 443
```

The client speaks plain TCP to the gateway on 9100, and APISIX does the TLS handshake with the Service on 443. The `ApisixUpstream` has to carry the same name as the Service, since that is how the stream backend finds it.

The port also needs to be open for stream traffic on the data plane:

```yaml
apisix:
  proxy_mode: http&stream
  stream_proxy:
    tcp:
      - 9100
```

One thing worth knowing: when the client connects over plain TCP there is no SNI to pass along, so APISIX sends `apisix_backend` as a dummy SNI to the upstream. If your upstream picks a certificate by SNI, or you are verifying the hostname, that is the value it will see.

On the Gateway API side the equivalent is a `TCPRoute` with a `BackendTrafficPolicy` carrying `scheme: tls`.

Would you be able to try this on 2.2.0? If it covers your case we can close this one out.
