### ISSUE TITLE
feat: Support logical operators for route expressions

### ISSUE THREAD

**Issue by huhamhire** [apache/apisix-ingress-controller#2261]
### Description

APISIX supports logical operators to combine multiple expressions.

e.g.
```json
[
    "AND",
    ["arg_version", "==", "v2"],
    [
        "OR",
        ["arg_action", "==", "signup"],
        ["arg_action", "==", "subscribe"]
    ]
]
```
https://docs.api7.ai/apisix/reference/apisix-expressions#logical-operators

However, the `ApisixRoute` CRD only supports selecting route when "one of the expression is matched".

There is no clue about how to use logical operators by declarative ways. Neither from the document, nor from source code.

**Comment by kayx23** [comment]
This seems to translate to an `AND`:

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
    - name: httpbin-route
      match:
        paths:
          - /anything
        methods:
          - GET
        exprs:
        - subject:
            scope: Header
            name: X-Foo
          op: Equal
          value: bar
        - subject:
            scope: Header
            name: X-Foo-1
          op: Equal
          value: bar1
      backends:
        - serviceName: httpbin
          servicePort: 80
```

<img width="973" alt="image" src="https://github.com/user-attachments/assets/771b7201-124a-44bb-9eb3-a1426831bb13">

```text
"vars": [
  ["http_x_foo","==","bar"],
  ["http_x_foo_1","==","bar1"]
]
```

But not sure how to make it an `OR`; or create a more complex composite logic. I checked the test cases and don't see anything relevant.
