### ISSUE TITLE
docs: How to configure an upstream from an autogenerated (service) backend via CRDs?

### ISSUE THREAD

**Issue by martin-schulze-e2m** [apache/apisix-ingress-controller#2267]
### Current State

I could find no documentation about how to do this. My understanding was, that the upstream should be named the same as the referenced service and be in the same namespace but I still get:

`ApisixIngress synced failed, with error: upstream doesn't exist. It will be created after ApisixRoute is created referencing it.`

For a concrete example:
```
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: bitter
spec:
  timeout:
    read: 180s
```

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: bitter
spec:
  http:
    - backends:
        - serviceName: bitter
          servicePort: 80
      match:
        hosts:
          - bitter.test
        paths:
          - /*
      name: route-open
```

I can see that this backend creates an upstream called `default_bitter_80` but the upstream config is not applied (as told by the error message). Similarly, I can't name the Upstream `default_bitter_80` because K8s forbids `_`, so how am I supposed to get this to match?

### Desired State

Describe how one can configure the autogenerated upstream from a backend route.

**Comment by kayx23** [comment]
I have run into `upstream doesn't exist. It will be created after ApisixRoute is created referencing it.` but once I created the service with route into referring to the upstream, the error goes away and things are configured.

All I did was I made sure these correspond: 

<img width="398" alt="image" src="https://github.com/user-attachments/assets/f75b593b-bfde-43f9-b752-408f22405ba2">

and that you create the ApisixRoute first and ApisixUpstream second.

**Comment by martin-schulze-e2m** [comment]
I deleted the upstream and upgraded the helm chart that creates both route and upstream. Still the same error despite the route existing before the upstream.

**Comment by martin-schulze-e2m** [comment]
I reproduced this on a local test cluster with `log_level: debug` in the ingress controller and got this additional message:
```
debug	apisix/upstream.go:43	try to look up upstream	{"name": "default_bitter_80_service"
```
However, as I said, the actual upstream name is `default_bitter_80`, so no wonder there is no match.

Please note that I am relying on the bitnami chart version 3.3.9.

**Comment by martin-schulze-e2m** [comment]
I would still like to get this working as it prevents upgrades.

**Comment by rizalalfarizi123** [comment]
> I'm having the same issue. ApisixUpstream is not working in the latest version.

any updates?

**Comment by joshualyon** [comment]
I'm experiencing what appears to be a similar issue. The logs show an error similar to what @martin-schulze-e2m mentioned where one of the logged errors says it failed to get the upstream where there is `_service` appended to the name it's trying to look up and the automatically created upstream (from the ApisixRoute) doesn't have the `_service` appended. 

Interestingly, the upstream **does** successfully get updated with the `healthCheck.active.httpPath` specified in the associated `ApisixUpstream`, so it seems like the APISIX Ingress Controller might be updating things successfully using the correct name, but perhaps is also trying using other conventions like the `_service` suffixed name, hash id, etc? 🤔

> [!WARNING]  
> While that wouldn't be a major issue if the Apisix Ingress Controller tried the additional conventions a handful of times, it seems like it **will endlessly retry  and fills up the `apisix-ingress-controller` logs**. 

For reference, I verified the upstreams by port forwarding 9180 from the `apisix-admin` service and doing a simple curl against the admin API like:
```
 curl http://127.0.0.1:9180/apisix/admin/upstreams -H 'X-API-Key: {YOUR-ADMIN-KEY}' | jq .
```

_(where the default admin key is `edd1c9f034335f136f87ad84b625c8f1` if you haven't changed it)_

## Logs
```
warn apisix/apisix_upstream.go:489 sync ApisixUpstream failed, will retry {"object": {"Type":4,"Object":{"Key":"default/httpbin-ngx-svc","OldObject":null,"GroupVersion":"apisix.apache.org/v2"},"OldObject":null,"Tombstone":null}, "error": "not found"}
error apisix/apisix_upstream.go:333 failed to get upstream default_httpbin-ngx-svc_80_service: not found
warn apisix/cluster.go:1164 upstream not found {"id": "e9357f4d", "url": "http://apisix-admin.ingress-apisix.svc.cluster.local:9180/apisix/admin/upstreams/e9357f4d", "cluster": "default"}
```

# Example Resources
#### `app-hello-deploy.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-ngx-deploy
  labels:
    app: httpbin-ngx
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: httpbin-ngx
  template:
    metadata:
      labels:
        app: httpbin-ngx
    spec:
      containers:
        - name: httpbin-ngx
          image: nginxdemos/hello:latest
```

#### `app-hello-svc.yaml`
```
apiVersion: v1
kind: Service
metadata:
  name: httpbin-ngx-svc
  labels:
    app: httpbin-ngx # label for better resource grouping and querying
spec:
  selector:
    app: httpbin-ngx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
```

#### `apisix-route-test.yaml`
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: route-hello-test
spec:
  http:
    - name: hello-test
      match:
        hosts:
          - hello-test.demo.com
        paths:
          - /*
      # Use a Kubernetes Service directly as the backend
      backends:
        - serviceName: httpbin-ngx-svc
          servicePort: 80
```

#### `apisix-upstream-test.yaml`
```
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: httpbin-ngx-svc # match the service name
spec:
  healthCheck:
    active:
      type: http  # default: http
      httpPath: /foo?health=4
```
