### ISSUE TITLE
request help: namespaceSelector

### ISSUE THREAD

**Issue by kworkbee** [apache/apisix-ingress-controller#2282]
### Issue description

I'm running multiple APISIX Ingress Controller in the same cluster. I'm specifying `namespaceSelector` because resources need to be isolated at the namespace level, but it seems to be working differently in version 1.7.0 and version 1.8.0.

For example, two namespaces are each
```yaml
metadata:
  name: A
  labels:
    gateway.apache.org/type: GLOBAL
    gateway.apache.org/env: DEV
```

```yaml
metadata:
  name: B
  labels:
    gateway.apache.org/type: OPENAPI
    gateway.apache.org/env: DEV
```

It has a label like and it's a namepace Selector

```
namespaceSelector:
- gateway.apache.org/type=OPENAPI
- gateway.apache.org/env=DEV
```
Assuming that you have designated it as,

Version 1.7.0 of Ingress Controller reads **only resources deployed in B Namespace**,
while version 1.8.0 of Ingress Controller reads **all resources deployed in A and B Namespace**.

There are no documents involved, so it is necessary to check that this is the intended action.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.7.0/1.8.0
- your Kubernetes cluster version (output of kubectl version): 1.29.6
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): AWS EKS
