### ISSUE TITLE
request help: How to use file-logger in apisix-ingress-controller?

### ISSUE THREAD

**Issue by sologgfun** [apache/apisix-ingress-controller#2312]
### Issue description

I used the YAML file below to create an ApisixRoute and the file-logger plugin. To view the logs, I ran the following command:

```
kubectl logs -f ingress-apisix-composite-deployment-686d9cccc5-n5f7t -n ingress-apisix ingress-apisix
```

This showed that the plugin was correctly loaded. Based on my understanding, there should be a corresponding `file.log` within the APISIX container, but it is not present.(echo plugin to test is worked)

I deploy apisix-ingress with this article https://apisix.apache.org/zh/blog/2023/10/18/ingress-apisix/.

Is there something I missed?where my **file.log**

<img width="1228" alt="image" src="https://github.com/user-attachments/assets/439a0350-5464-4a56-a957-2edb49dccf9c">

```
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: file-logger-config
  namespace: test
spec:
  plugins:
  - name: file-logger
    enable: true
    config:
      "path": "logs/file.log"
      
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: kcs-route
  namespace: test
spec:
  http:
    - name: kcs-backend
      priority: 1
      websocket: true
      match:
        paths:
          - "/dd/*"
      backends:
        - serviceName: kcs-console-vue
          servicePort: 8088
      plugin_config_name: file-logger-config
```

### Environment

apisix-ingress-controller version is 1.7.0
