### ISSUE TITLE
request help: upstream and route not created using argocd

### ISSUE THREAD

**Issue by rizalalfarizi123** [apache/apisix-ingress-controller#2323]
### Issue description

i have two apisix resource, route and upstream

```
# upstream.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: finance-service-upstream
spec:
  externalNodes:
  - type: Service
    name: finance-service
```

and

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: finance-service-route
spec:
  http:
    - name: get-sales-units-records-route
      match:
        paths:
        - /api/v1/system-configurations/sales-units/records
        methods:
        - GET
      upstreams:
      - name: finance-service-upstream
```
after sync with argo, i got error
```
upstream:
ApisixIngress synced failed, with error: upstream doesn't exist. It will be created after ApisixRoute is created referencing it.
```
```
route:
ApisixIngress synced failed, with error: 1 error occurred: * unexpected status code 400; error message: {"error_msg":"failed to fetch upstream info by upstream id [8cd0a3a0], response code: 404"}
```

this is my kustomize resource order
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../applications/finance-service/
- ./route-list.yaml
- ./route-upstream.yaml

commonLabels:
  env: development

patches:
- path: ./patches/deployment.yaml
```

namespace of all resource are the same
namespace for apisix is: `platform`

i read that upstream will be created if we reference it in route, but i doesn't work with me

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.8.2
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
