### ISSUE TITLE
request help: 通过 ingress controller 配置路由的时候，文档描述有问题

### ISSUE THREAD

**Issue by wfy-belief** [apache/apisix-ingress-controller#2331]
### Issue description

配置 TCP 四层代理的时候，根据文档来配置 https://apisix.apache.org/docs/ingress-controller/references/apisix_route_v2/
![image](https://github.com/user-attachments/assets/fe71b929-61d1-4cce-865c-24808abee828)

根据文档描述，配置 stream 参数的时候，发现这个地方文档是不是有错误

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: mysql-stream-route
spec:
  stream:
    - name: mysql-master
      protocol: TCP
      match:
        ingressPort: 3306
  http:
    - backends:
        - serviceName: mysql
          servicePort: 3306
```

结果如下：
```bash
The ApisixRoute "redis-stream-route" is invalid: 
* <nil>: Invalid value: "": "spec.http[0]" must validate at least one schema (anyOf)
* spec.http[0].name: Required value
* spec.http[0].match: Required value
* spec.stream[0].backend: Required value
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
使用的最新版 1.8.0
```
helm upgrade --install apisix apisix/apisix --create-namespace  --namespace apisix --set dashboard.enabled=true --set ingress-controller.enabled=true --set ingress
-controller.config.apisix.serviceNamespace=apisix
```
- your Kubernetes cluster version (output of kubectl version):
```bash
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.30.5+k3s1
```
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
Ubuntu 24.04 LTS   6.8.0-40-generic   containerd://1.7.21-k3s2
