### ISSUE TITLE
request help: how to forward traffic to custom nodes with static ip

### ISSUE THREAD

**Issue by cataglyphis** [apache/apisix-ingress-controller#2362]
### Issue description

- deploy service in ECS nodes out of K8s
- deploy apisix and apisix route in k8s
- forward traffic to service

```
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: automq
  namespace: automq
spec:
  scheme: http
  loadbalancer:
    type: roundrobin
  timeout:
    connect: 6s
    read: 6s
    send: 6s
  passHost: node
  nodes:
    - host: 10.110.0.3
      port: 8080
      weight: 1
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: automq
  namespace: automq
spec:
  http:
    - name: automq-http
      match:
        hosts:
          - xxx.org
        paths:
          - /*
      websocket: false
      upstreams:
        - name: automq
          weight: 100

```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.8.3
- your Kubernetes cluster version (output of kubectl version): 1.26
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
