### ISSUE TITLE
🚀 Support for k8s.apisix.apache.org/headers and rewrite-uri annotations missing in v1.8.4

### ISSUE THREAD

**Issue by m4dm4rtig4n** [apache/apisix-ingress-controller#2414]
## Bug / Feature Request

In APISIX Ingress Controller version `v1.8.4`, annotations related to the `proxy-rewrite` plugin are not complete when defined on an Ingress resource.

## Environment

* APISIX Ingress Controller version: `v1.8.4`
* Kubernetes version: `v1.28.x`
* Installation method: Helm
* Mode: Ingress resource (not ApisixRoute)

## Expected Behavior

When defining the following annotations on a standard `Ingress`, I expect them to configure the `proxy-rewrite` add/set/remove header automatically in the route created by APISIX:

```yaml
annotations:
  k8s.apisix.apache.org/rewrite-target-regex: ^/api/authentication/(.*)
  k8s.apisix.apache.org/rewrite-target-regex-template: "/$1"
  k8s.apisix.apache.org/rewrite-target-add-header: X-Forwarded-For:$remote_addr
  k8s.apisix.apache.org/rewrite-target-set-header: "X-Api-Engine:apisix,X-Api-Version:v1,X-Api-useless:"
  k8s.apisix.apache.org/rewrite-target-remove-header: "Cookie"
```

Thanks for your great work!
