### ISSUE TITLE
discuss: ApisixRoute change struct

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-ingress-controller#248]

**Comment by tokers** [comment]
The `ApisixRoute` should leverage the advantages of APISIX Routes as soon as possible, for instance, the flexible route match, native plugins support.

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - paths:
       - "/a"
       - "/bb*"
  priority: 10
  methods:
    - GET
    - POST
  hosts:
    - a.com
    - aa.com
  remote_addrs:
    - 192.168.1.0/24
    - 10.0.5.12
  nginxVars:
    - "$binary_remote_addr"
  route:
    serviceName: httpbin
    servicePort: 8080
  plugins:
    - name: redirect
       enable: true
       config:
         aaa: bbb
         ccc: ddd
```

The `scripts` are used by plugin orchestration, we don't use it.

**Comment by tokers** [comment]
@gxthrj

**Comment by gxthrj** [comment]
I think it might be a good idea to keep the `pathtype`, the structure is more expressive than `*`, and it will be easy to expand

**Comment by gxthrj** [comment]
Are `priority` and `match` the same level ?

**Comment by gxthrj** [comment]
I think  it is more readable using `upstream` instead of `route` 
Such as
```yaml
upstream:
  serviceName: xxx
  servicePort: xxx
```
