### ISSUE TITLE
request help: Getting route not found issue

### ISSUE THREAD

**Issue by Bhanuji95** [apache/apisix-ingress-controller#259]
### Development

* apisix version: 2.2
* OS: APISIX docker image (ubuntu)
* OpenResty / Nginx version: openresty/1.19.3.1
* etcd version: 3.4.8

we have also added apisix route and upstream.

**Comment by Bhanuji95** [comment]
Hello,

Below is the ingress configuration I used.

## Upstream ##
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: myapp
spec:
  ports:
  - port: 80
    loadbalancer:
      type: chash
      hashOn: header
      key: 
---
## Route ##
apiVersion: apisix.apache.org/v1
kind: ApisixRoute
metadata:
  name: myapp
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: 80
        path: /path*

A log from ingress controller says: E0222 22:24:19.709891 1 leaderelection.go:325] error retrieving resource lock default/ingress-apisix-leader: leases.coordination.k8s.io "ingress-apisix-leader" is forbidden: User "system:serviceaccount:default:apisix-view-serviceaccount" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "default"

**Comment by tokers** [comment]
@Bhanuji95 How did you install apisix-ingress-controller and apisix?

**Comment by Bhanuji95** [comment]
Hello @tokers,

we installed using docker images and followed official installation document, below are the details:

etcd: quay.io/coreos/etcd:v3.4.8
apisix-gw: apache/apisix:latest
ingress: apache/apisix-ingress-controller:0.3.0

**Comment by tokers** [comment]
It weird since the permission missing problem was fixed in `0.3.0`.

**Comment by tokers** [comment]
@Bhanuji95 Could you please paste the contents of the serviceaccount `apisix-view-serviceaccount`.

**Comment by Bhanuji95** [comment]
Hello @tokers,

I am giving my serviceaccount, cluster role and role binding information here

```
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: apisix-view-serviceaccount
  namespace: default
secrets:
  - name: apisix-view-serviceaccount-token-hhmp4
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apisix-view-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: apisix-view-serviceaccount
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apisix-view-clusterrole
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apisix-view-clusterrole
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apisix.apache.org
    resources:
      - apisixroutes
      - apisixupstreams
      - apisixservices

```
