### ISSUE TITLE
bug: Service cannot be dynamically aware of changes to the service when it is deleted and rebuilt again

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#276]
### Issue description
When there is a problem with upstream resource configuration, delete the service corresponding to upstream POD and re-expose it.A look at the Apisix-Ingress log shows that it also monitors old services。
This is deploymen yaml of  pod :

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
```

This is  service yaml  of pod : --- there is  problematic  because my apisix-ingress is gray-publish of namespace  , this servicde  can't be discove

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-03-02T02:48:52Z"
  labels:
    app: web
  name: web
  namespace: default 
found
  resourceVersion: "13882151"
  selfLink: /api/v1/namespaces/default/services/web
  uid: 0d434999-12bb-4dfa-9c93-e69d66290944
spec:
  clusterIP: 10.102.85.217
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32712
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

```

This is my apisix-upstream.yaml:
```
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: web
spec:
  ports:
  - port: 80
    loadbalancer:
      type: chash
      hashOn: cookie
      key: sid1
```

when I  use  kubectl  apply -f   apisix-upstream.yaml to  create  upstream CRD , Appear error ： 
E0302 10:59:37.243624       1 apisix_upstream.go:113] error syncing 'default/web': list upstreams failed, err: Get http://apisix-admin:9180/apisix/admin/upstreams: dial tcp: lookup apisix-admin on 10.96.0.10:53: server misbehaving。 
So  I  use commamd  kubectl  delete -f   apisix-upstream.yaml  and modifi  apisix-upstream.yaml  then change the namespace to gray-publish.  But   the error log is the same as last time ：
E0302 11:11:37.340643       1 apisix_upstream.go:113] error syncing 'default/web': list upstreams failed, err: Get http://apisix-admin:9180/apisix/admin/upstreams: dial tcp: lookup apisix-admin on 10.96.0.10:53: server misbehaving。
