### ISSUE TITLE
Support Traffic Split in ApisixRoute

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#289]
We have a [traffic split plugin](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/traffic-split.md) in Apache APISIX, but it's not easy to use it in Ingress scenario because there are some resource reference relationships like `upstream_id`.

In consideration of the widely use of traffic split in Ingress, Service Mesh, I'd like to implement this function into ApisixRoute, as the first class feature, rather than using the plugin mechanism. Just like what the [TrafficSplit](https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-split/v1alpha4/traffic-split.md) resource do in [SMI](https://github.com/servicemeshinterface/smi-spec).

Currently, the ApisixRoute v2alpha1 supports to configure one backend, we may extend it as the following:

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - httpbin.com
      paths:
      - /ip
    backend:
      serviceName: httpbin
      servicePort: 80
  - name: rule2
     match:
       hosts:
       - httpbin.com
       paths:
       - /status
     weightedBackends:
     - serviceName: httpbin
        servicePort: 80
        weight: 100
     - serviceName: httpbin2
        servicePort: 8080
        weight: 50
```

We can add a new field `weightedBackends`, which is exclusive with `backend` field, the `weightedBackends` contains a couples of backends, each one specifying a Service (name, port) and its weight.

when `weightedBackends` exists, the traffic split plugin will be enabled in the ultimate APISIX Route resource (but is invisible from users).

Note since the traffic plugin also supports users to configure match conditions but it's not required in ApisixRoute scenario, the match conditions are written in `match` field, so the generated plugin config won't have the match field.

**Comment by juzhiyuan** [comment]
Not familiar with this temporarily, just one point: how about using `serviceWithWeight` instead of `weightedBackends`?

**Comment by Junnplus** [comment]
`weightedBackends` and `backend` can be unified?  But the weight are different, default weight 100.

**Comment by tokers** [comment]
> `weightedBackends` and `backend` can be unified? But the weight are different, default weight 100.

Maybe we can allow user to ignore the weight when there is only one backend.

**Comment by tokers** [comment]
> Not familiar with this temporarily, just one point: how about using `serviceWithWeight` instead of `weightedBackends`?

Just like @Junnplus , We can unify the `weightedBackends` and `backend`.

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - httpbin.com
      paths:
      - /ip
    backend:
      serviceName: httpbin
      servicePort: 80
  - name: rule2
     match:
       hosts:
       - httpbin.com
       paths:
       - /status
     backends:
     - serviceName: httpbin
        servicePort: 80
        weight: 100
     - serviceName: httpbin2
        servicePort: 8080
        weight: 50
```

But the `backend` is used as an object, we may use another field `backends`, and telling people to use the `backends` field.In the future release, we may deprecate the `backend` field and even delete it.

**Comment by gxthrj** [comment]
It looks like we only support weight.
There are  some canary feature In [traffic split plugin](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/traffic-split.md) . 
How about add `match` rules in backends ?

**Comment by tokers** [comment]
> It looks like we only support weight.
> There are some canary feature In [traffic split plugin](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/traffic-split.md) .
> How about add `match` rules in backends ?

That's really, what about the following configuration snippet:

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - httpbin.com
      paths:
      - /ip
    backend:
      serviceName: httpbin
      servicePort: 80
  - name: rule2
     match:
       hosts:
       - httpbin.com
       paths:
       - /status
     backends:
     - match:
         nginxVars:
         - subject: http_user_agent
           op: RegexMatchCaseInsensitive
           value: ".*Mozilla.*"
       backend:
         serviceName: httpbin
         servicePort: 80
         weight: 100
     - backend: # default backend, always configured it
         serviceName: httpbin2
         servicePort: 8080
         sweight: 50
```

**Comment by gxthrj** [comment]
The `weight` configuration of the `match` part is confusing.
It seems that after being matched by `match`, people can continue to control the traffic through `weight`. So the `backend` with `match` should be `backends`.

Another point is about the default backend. 
The default backends can be multiple, so that `weight` is meaningful.

BTW,  there is a typo `sweight` in default backends , should be `weight`.

**Comment by tokers** [comment]
> The `weight` configuration of the `match` part is confusing.
> It seems that after being matched by `match`, people can continue to control the traffic through `weight`. So the `backend` with `match` should be `backends`.
> 
> Another point is about the default backend.
> The default backends can be multiple, so that `weight` is meaningful.
> 
> BTW, there is a typo `sweight` in default backends , should be `weight`.

I changed my mind, the canary release can be implemented by multiple rules in `spec.http`, for instance:

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - httpbin.com
      paths:
      - /ip
    backend:
      serviceName: httpbin
      servicePort: 80
  - name: rule2
     match:
       hosts:
       - httpbin.com
       paths:
       - /ip
       nginxVars:
         subject: http_user_agent
         op: Equal
         value: Mozilla
     backend:
        serviceName: httpbin-2
        servicePort: 80
```

If people want to implement the traffic shifting by weighted backends, they can do like this:

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule1
     match:
       hosts:
       - httpbin.com
       paths:
       - /status
     backends:
     - serviceName: httpbin
        servicePort: 80
        weight: 100
     - serviceName: httpbin2
        servicePort: 8080
        weight: 50
```

**Comment by gxthrj** [comment]
I think the newer proposal implemented by multiple rules in `spec.http` is better and more clear.

But still a point to note.
The order of the rules which has the same `host` and `vars`. We need the `priority ` the same as the route in APISIX.

**Comment by tokers** [comment]
@gxthrj We already support to specify `priority` field in `ApisixRoute/v2alpha1`.

**Comment by gxthrj** [comment]
OK, Need to be set in previous example.

**Comment by gxthrj** [comment]
```
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - httpbin.com
      paths:
      - /ip
      priority: 100 // set priority for the rules which has the same host and uri
    backend:
      serviceName: httpbin
      servicePort: 80
  - name: rule2
     match:
       hosts:
       - httpbin.com
       paths:
       - /ip
      priority: 200 // set priority for the rules which has the same host and uri
       nginxVars:
         subject: http_user_agent
         op: Equal
         value: Mozilla
     backend:
        serviceName: httpbin-2
        servicePort: 80
```
