### ISSUE TITLE
bug: route vars configure synchronization data exceptions

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#322]
### Issue description
When I configured two rules in route.yaml, one carried the rules and the other did not ,Routes with rules are placed on top and routes without rules are placed below.Use the following configuration
``` yaml
apiVersion: apisix.apache.org/v2alpha1apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
 name: test
spec:
 http:
 - name: rule1
   match:
     paths:
       - /*
     exprs:
     - subject:
         scope: Cookie
         name: name
       op: RegexMatch
       value: ".*lisi.*"
   backend:
     serviceName: web-huido
     servicePort: 80
 - name: rule2
   match:
     paths:
       - /*
   backend:
     serviceName: web-shengchan
     servicePort: 80
```
```
{"id":"52b54be8","status":1,"vars":[["cookie_name","~~",".*lisi.*"]],"uris":["\/*"],"priority":0,"update_time":1617071198,"upstream_id":"450a096f","create_time":1617071198,"desc":"default_test_rule1"}
{"id":"cbbc1a52","status":1,"vars":[["cookie_name","~~",".*lisi.*"]],"uris":["\/*"],"priority":0,"update_time":1617071198,"upstream_id":"1ef7ab88","create_time":1617071198,"desc":"default_test_rule2"}
```

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
apisix-ingress-controller version: now master  apisix: apache/apisix:2.4-centos
* your Kubernetes cluster version (output of `kubectl version`);
v 1.17.8
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue

1.
2.
3.
