### ISSUE TITLE
bug: the priority configuration could not take effect

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#326]
### Issue description
I configured the priority generic type in route.yaml ,but the generic type is not synchronized to Apisix.
this is my route.yaml 
``` yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
 name: test-cookie
 namespace: default
spec:
 http:
 - name: rule1
   priority: 0
   match:
     paths:
       - /*
   backend:
     serviceName: web2
     servicePort: 80
 - name: rule2
   priority: 2
   match:
     paths:
       - /*
     exprs:
     - subject:
         scope: Cookie
         name: name
       op: Equal
       value: zhangsan
   backend:
     serviceName: web1
     servicePort: 80
```
When I execute the command kubectl apply-f roue.yaml and check the configuration of apisix, I find that the priority configuration is not successful.
etcd:
`{"status":1,"uris":["\/*"],"priority":0,"update_time":1617245342,"id":"bfd0375a","create_time":1617245342,"desc":"default_test-cookie_rule2","upstream_id":"e3dca044","vars":[["cookie_name","==","zhangsan"]]}`
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
apisix-ingress-controller version is the current master(2021/3/24 )
apisix image version is   2.4-centos
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
