### ISSUE TITLE
request help: Support for grayscale scenes

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#399]
### Issue description
In a grayscale scenario, the grayscale upstream service and the production upstream service belong to different namespaces when switching environments.Routing configuration based on apisix-ingress-Controller is now cumbersome: only one namespace can be specified in each route configuration file and that namespace must be in the same namespace as the service below. Can the namespace configuration be placed in each route for greater flexibility
My needs are as follows:
Now this is all for production time configuration
```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
 name: test-cookie
 namespace: prod-namespace
spec:
 http:
 - name: rule1
   priority: 1
   match:
     paths:
       - /*
   backends:
     - serviceName: web3
       servicePort: 81
       weight: 70
     - serviceName: web2
       servicePort: 81
       weight: 30
 - name: rule2
   priority: 0
   match:
     paths:
       - /*
     exprs:
     - subject:
         scope: Cookie
         name: name
       op: Equal
       value: zhangsan
     - subject:
         scope: Header
         name: name
       op: NotEqual
       value: lisi
   backend:
     serviceName: web2
     servicePort: 81
```
But next time I need to switch the upstream of Routed rule2 ,and  Routed rule2 current upstream service is in gray-namespace.
To do this, you have to split one configuration file into two yaml
one
``` yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
 name: test-cookie
 namespace: gray-namespace
spec:
 http:
 - name: rule1
   priority: 1
   match:
     paths:
       - /*
   backends:
     - serviceName: web3
       servicePort: 81
       weight: 70
     - serviceName: web2
       servicePort: 81
       weight: 30
```
another
```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
 name: test-cookie-111
 namespace:  prod-namespace
spec:
 http:
  - name: rule2
   priority: 0
   match:
     paths:
       - /*
     exprs:
     - subject:
         scope: Cookie
         name: name
       op: Equal
       value: zhangsan
     - subject:
         scope: Header
         name: name
       op: NotEqual
       value: lisi
   backend:
     serviceName: web2
     servicePort: 81
```
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
apisix-ingress-controller verison : 0.5.0
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment]
@pioneer-hash Why we don't support cross namespace reference is because crossing namespace might be the main course of privilege escalation attacks. See https://github.com/kubernetes/kubernetes/issues/17088.

For your case, you can still put them into one YAML file.

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
 name: test-cookie
 namespace: gray-namespace
spec:
 http:
 - name: rule1
   priority: 1
   match:
     paths:
       - /*
   backends:
     - serviceName: web3
       servicePort: 81
       weight: 70
     - serviceName: web2
       servicePort: 81
       weight: 30
---
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
 name: test-cookie-111
 namespace:  prod-namespace
spec:
 http:
  - name: rule2
   priority: 0
   match:
     paths:
       - /*
     exprs:
     - subject:
         scope: Cookie
         name: name
       op: Equal
       value: zhangsan
     - subject:
         scope: Header
         name: name
       op: NotEqual
       value: lisi
   backend:
     serviceName: web2
     servicePort: 81
```
