### ISSUE TITLE
request help: ApisixRoute plugins configuration does not take effect

### ISSUE THREAD

**Issue by wgy-home** [apache/apisix-ingress-controller#532]
### Issue description
ApisixRoute customer  plugins configuration does not take effect。
yaml:
```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: test
spec:
  http:
    - name: test
      match:
        hosts:
        - test.cn
        paths:
          - /*
      backends:
        - serviceName: test-svc
          servicePort: 80
      plugins:
        - name: jwt
          enable: true
          redis_host: 10.200.99.2
          redis_port: '6379'
          whitelist_uri:
            - /api/pad/user/logi
```

Plug-in JWT is a custom plug-in，It requires configurations such as Redis Host and Redis Port，The plug-in has been started, but the configuration has not taken effect，Is there something wrong with my YAML configuration？Please help me, thanks！

The plug-in has been started, but the configuration has not taken effect.
![image](https://user-images.githubusercontent.com/10112569/120955248-87ec8500-c783-11eb-82ea-5b423860c065.png)

### Environment

* apisix-ingress-controller version: 
version: 0.5.0
Git SHA: 
Go Version: go1.13.8
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
*  kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
* apisix version 2.5

**Comment by wgy-home** [comment]
My YAML configuration is wrong, need to add config

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: test
spec:
  http:
    - name: test
      match:
        hosts:
        - test.cn
        paths:
          - /*
      backends:
        - serviceName: test-svc
          servicePort: 80
      plugins:
        - name: jwt
          enable: true
              config:
              redis_host: 10.200.99.2
              redis_port: '6379'
              whitelist_uri:
                - /api/pad/user/logi
```

**Comment by wgy-home** [comment]
My YAML configuration is wrong, need to add config

```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: test
spec:
  http:
    - name: test
      match:
        hosts:
        - test.cn
        paths:
          - /*
      backends:
        - serviceName: test-svc
          servicePort: 80
      plugins:
        - name: jwt
          enable: true
              config:
              redis_host: 10.200.99.2
              redis_port: '6379'
              whitelist_uri:
                - /api/pad/user/logi
```
