### ISSUE TITLE
bug: Should not call func recordStatus when only delete ApisixUpstream

### ISSUE THREAD

**Issue by chzhuo** [apache/apisix-ingress-controller#582]
### Issue description

https://github.com/apache/apisix-ingress-controller/blob/master/pkg/ingress/apisix_upstream.go#L194
In above file should not call recordStatus when only delete ApisixUpstream

### Environment
apisix-ingress-controller version 1.0.0-4b16e28-go1.16.3

### Minimal test code / Steps to reproduce the issue
upstream.yaml
```yaml
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: whoami
spec:
  timeout:
    connect: 6s
    read: 10s
    send: 10s
```

1.kubectl apply -f upstream.yaml
2.kubectl delete -f upstream.yaml

### What's the actual result? (including assertion message & call stack if applicable)
![image](https://user-images.githubusercontent.com/10919124/125410377-6bc9ac80-e3ef-11eb-8fc3-30528dd68775.png)

### What's the expected result?
should no error
