### ISSUE TITLE
bug: sync ingress failed, will retry

### ISSUE THREAD

**Issue by liov** [apache/apisix-ingress-controller#594]
### Issue description
```bash
sync ingress failed, will retry	{"object": {"Type":1,"Object":{"Key":"ingress-apisix/apisix-dashboard","GroupVersion":"networking/v1","OldObject":null},"Tombstone":null}, "error": "2 errors occurred:\n\t* json: cannot unmarshal number into Go struct field listResponse.count of type string\n\t* json: cannot unmarshal number into Go struct field listResponse.count of type string\n\n"}
```
### Environment
```bash
NAME                     	NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART                          	APP VERSION
apisix                   	ingress-apisix	1       	2021-07-15 15:27:32.252837995 +0800 CST	deployed	apisix-0.3.5                   	2.7.0      
apisix-dashboard         	ingress-apisix	1       	2021-07-15 12:23:36.58831042 +0800 CST 	deployed	apisix-dashboard-0.1.5         	2.7.0      
apisix-ingress-controller	ingress-apisix	1       	2021-07-15 15:40:21.419281906 +0800 CST	deployed	apisix-ingress-controller-0.5.0	1.0.0 
```
```bash
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

### Minimal test code / Steps to reproduce the issue

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apisix-dashboard
  namespace: ingress-apisix
spec:
  # apisix-ingress-controller is only interested in Ingress
  # resources with the matched ingressClass name, in our case,
  # it's apisix.
  ingressClassName: apisix
  rules:
  - host: dashboard.apisix.org
    http:
      paths:
      - backend:
          service:
            name: apisix-dashboard
            port:
              number: 80
        path: /
        pathType: Prefix
```

### What's the actual result? (including assertion message & call stack if applicable)
404 NOT Routes
