### ISSUE TITLE
docs: Improve practices document,apisix.apache.org/v2alpha1 is deprecated

### ISSUE THREAD

**Issue by zengzhengrong** [apache/apisix-ingress-controller#597]
https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices/proxy-the-httpbin-service.md
```
# httpbin-route.yaml
apiVersion: apisix.apache.org/v2beta1
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backend:
        serviceName: httpbin
        servicePort: 80
```

apiVersion: apisix.apache.org/v2beta1 is deprecated, use apisix.apache.org/v2alpha1
