### ISSUE TITLE
My apisix-ingress-controller report a problem .

### ISSUE THREAD

**Issue by sober-wang** [apache/apisix-ingress-controller#649]
### Issue description
```
E0824 17:23:23.970756       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: the server could not find the requested resource
```

### Environment
- my apisix version: 2.7
- my apisix-ingress-controller: apisix-ingress-controller version 0.5.0-43e4d11-go1.13.8
- my kubernetes version: 1.18.2 

kubernetes  yaml  file 
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myhttp-ingress
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  rules:
  - host: myhttp.test.io
    http:
      paths:
      - backend:
          serviceName: myhttp-svc
          servicePort: 9527
        path: /myhttp

```
