### ISSUE TITLE
request help: ingress/apisixroute without physical service backends

### ISSUE THREAD

**Issue by Iced-Sun** [apache/apisix-ingress-controller#664]
### Issue description

The issue is related to #661.

I suggest that `apisix-ingress-controller` could implement a complete annotation mechanism in Ingress/ApisixRoute to configure the routes.

A similar approach could be found in aws-load-balancer-controller (see [actions](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#actions) and [conditions](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#conditions)).

Here is a possible demonstration to enable http-to-https redirection using nginx variable of `$proxy_protocol_server_port`:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    k8s.apisix.apache.org/actions.ssl-redirect: >
      {"plugins":{"redirect":{"uri":"https://$host$request_uri","ret_code":301}}}
    k8s.apisix.apache.org/conditions.ssl-redirect: >
      {"vars":[["proxy_protocol_server_port","==","80"]],"priority":10}
    k8s.apisix.apache.org/actions.fixed-response: >
      {"plugins":{"response-rewrite":{"status_code":503,"body":"503"}}}
spec:
  ingressClassName: apisix
  rules:
    # rule-1: default forward to httpbin
    - http:
        paths:
          - backend:
              service:
                name: httpbin
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: fixed-respone
                port:
                  name: use-annotation
            path: /503
            pathType: Exact
    # rule-2: forward my-service.example.com to my-service
    - host: my-service.example.com
      http:
        paths:
          - backend:
              name: my-service
              port:
                number: 80
          - backend:
              name: ssl-redirect
              port:
                name: use-annotation
```

The above ingress would be essentially translated to the following apisix routes:
1. `.spec.rules[0].http.paths[0]`
```js
{
  "uris": [ "/", "/*"],
  "upstream_id": "<generated>"
}
```

2. `.spec.rules[0].http.paths[1]`
```js
{
  "uris": [ "/503"],
  "plugins": {
    "response-rewrite": {
      "status_code":503,
      "body":"503"
    }
  }
}
```

3. `.spec.rules[1].http.paths[0]`
```js
{
  "uris": [ "/", "/*"],
  "host": "my-service.example.com",
  "upstream_id": "<generated>"
}
```

4. `.spec.rules[1].http.paths[1]`
```js
{
  "uris": [ "/", "/*"],
  "host": "my-service.example.com",
  "priority": 10,
  "vars": [
    [
      "proxy_protocol_server_port",
      "==",
      "80"
    ]
  ],
  "plugins": {
    "redirect": {
      "ret_code": 301,
      "uri": "https://$host$request_uri"
    }
  },
}
```

Is that viable?
