### ISSUE TITLE
bug: Informer recursively trigger update event

### ISSUE THREAD

**Issue by chzhuo** [apache/apisix-ingress-controller#682]
### Issue description
Informer recursively trigger `update`,  because  `recordStatus`

### Environment

apisix-ingress-controller: master branch commit 1e1be7401ba3707ba660a7d61df5118fc5725eff
k8s server:  v1.19.3
### Minimal test code / Steps to reproduce the issue

apisix-ingress-controller config:
```yaml
log_level: "debug"
kubernetes:
  kubeconfig: /home/chenzhuo/.kube/config
apisix:
  default_cluster_base_url: "http://10.0.5.14:9080/apisix/admin"
  default_cluster_admin_key: "edd1c9f034335f136f87ad84b625c8f1"
```
open the debug log,  you will see continuously log `ApisixRoute update event arrived`.  I founed that  https://github.com/apache/apisix-ingress-controller/blob/1e1be7401ba3707ba660a7d61df5118fc5725eff/pkg/ingress/status.go#L38  will recursively cause update event
