### ISSUE TITLE
bug: Ingress Status Load Balancer IPs Not Being Updated

### ISSUE THREAD

**Issue by myoss** [apache/apisix-ingress-controller#690]
### Environment

* apisix-ingress-controller version: 1.2.0
* your Kubernetes cluster version: ACK 1.20.4-aliyun.1;
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`): Linux demo 4.19.91-23.al7.x86_64 #1 SMP Tue Mar 23 18:02:34 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Minimal test code / Steps to reproduce the issue

1. ACK 1.20.4-aliyun.1
2. create Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
  namespace: default
spec:
  ingressClassName: apisix
  rules:
    - host: demo.example.com
      http:
        paths:
          - backend:
              service:
                name: svc-demo
                port:
                  number: 80
            path: /
            pathType: Prefix

```
3.

### What's the actual result? (including assertion message & call stack if applicable)
![Snipaste_2021-09-24_18-41-04](https://user-images.githubusercontent.com/6986459/134661969-ec598d35-5359-4126-ad6b-1065212818cd.jpg)

### What's the expected result?
![Snipaste_2021-09-24_18-40-02](https://user-images.githubusercontent.com/6986459/134662520-3089a9c7-0559-4152-b380-a95b7fbd30fe.jpg)
