### ISSUE TITLE
ApisixRoute route still work after deleting AR source 

### ISSUE THREAD

**Issue by LuChenjing** [apache/apisix-ingress-controller#700]
Using helm to install apisix and apisix-ingress-controller.
![image](https://user-images.githubusercontent.com/42744697/135398393-e96b77fe-4fe2-49de-b352-8fdcb230b0f4.png)
apisix version: image apache/apisix:2.7-alpine
apisix-ingress-controller: image apache/apisix-ingress-controller:1.1.0

Here is the ApisixRoute manifest yaml:
```yaml
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: observer-apisixroute
  namespace: onest-observer
spec:
  http:
    - name: prometheus-1
      match:
        paths:
          - /monitor1/*
      backend:
        serviceName: prometheus-monitoring-1
        servicePort: 9090
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/monitor1/(.*)"
              - "/$1"
    - name: prometheus-2
      match:
        paths:
          - /monitor2/*
      backend:
        serviceName: prometheus-monitoring-2
        servicePort: 9090
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/monitor2/(.*)"
              - "/$1"
    - name: grafana-rule
      match:
        paths:
          - /dashboard/*
      backend:
        serviceName: grafana-ha-svc
        servicePort: 3000
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/dashboard/(.*)"
              - "/$1"
```

**Issue1:** After applying the resource only shown URIS: /monitor1/*:
![image](https://user-images.githubusercontent.com/42744697/135398952-9786aebb-0784-4c87-88d2-c059d93882be.png)

Able to access prometheus1
![image](https://user-images.githubusercontent.com/42744697/135399385-670c822d-b7ad-4bd6-bbc6-b6a60f07cff2.png)

**Issue2:** Able to accesser by /monitor2/ but shown the page of prometheus1
![image](https://user-images.githubusercontent.com/42744697/135399694-31579308-6a62-49cb-9961-a1d1d8f1d6ad.png)

**Issue3:** After delete ApisixRoute, still able to access the prometheus1
![image](https://user-images.githubusercontent.com/42744697/135399982-bb7217d1-4094-442b-8596-dfa12dca0623.png)
![image](https://user-images.githubusercontent.com/42744697/135400287-83a9390c-6331-4e90-9fa8-89377b3e1ed7.png)
![image](https://user-images.githubusercontent.com/42744697/135400342-016cf22d-45b8-47bf-b5db-96570979ef0d.png)

**Comment by tokers** [comment]
1. Issue 1 is a CRD definition problem about the column printer.
2. For issue 2, could you paste the request/response details, you can use the curl utility.
3. Will try to reproduce the issue 3 on my local.

**Comment by LuChenjing** [comment]
Sure, For

> 1. Issue 1 is a CRD definition problem about the column printer.
> 2. For issue 2, could you paste the request/response details, you can use the curl utility.
> 3. Will try to reproduce the issue 3 on my local.

Sure, for issue2:
I got K8S service for prometheus1,2:
![image](https://user-images.githubusercontent.com/42744697/135645339-4d1f1e52-6514-4344-ac31-f83151f00988.png)

CURL the prometheus 2 with the nodePort service:
![image](https://user-images.githubusercontent.com/42744697/135645233-c4e730da-bcad-4682-86af-2d0e406f0a2c.png)
 
CURL the prometheus 2 with the exact apisix route path(**same with nodePort service**):
![image](https://user-images.githubusercontent.com/42744697/135645701-9e997b69-f15e-4fad-9dcd-05a2cced9978.png)

But not able to access the correct service on browser:
![image](https://user-images.githubusercontent.com/42744697/135646139-4bbb445a-32e7-468d-b424-143b6b7c52a8.png)

**Comment by tokers** [comment]
It seems that the configurations are correct, could you try to access the APISIX admin API and print all routes?

**Comment by gxthrj** [comment]
@LuChenjing 
I have sorted out your screenshots, the configuration is the same as expected, can you see if your understanding is wrong？

1. The configuration paragraph of `prometheus-2` in ApisixRoute resource
```yaml
- name: prometheus-2
      match:
        paths:
          - /monitor2/*
      backend:
        serviceName: prometheus-monitoring-2
        servicePort: 9090
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/monitor2/(.*)"
              - "/$1"
```

2. The Prometheus svc 
![image](https://user-images.githubusercontent.com/4413028/137064173-ab0e3700-26e0-4947-b586-401e37840c3d.png)

3. Request to Prometheus-2 directly
![image](https://user-images.githubusercontent.com/4413028/137064273-1c329670-821d-492c-8305-4a7663c6576e.png)

4. Request to Proemtheus-2 from APISIX 
[**The same result as request to Prometheus-2 directly, which is expected**]
![image](https://user-images.githubusercontent.com/4413028/137064354-2f7fb5ec-dfb6-410b-b0ef-645fbbd719a5.png)

5. But， Request to APISIX by `http://100.71.8.124:30005/api/v1/status/config` , I can not see the configure `/api/*` in `ApisixRoute` manifest yaml. So we can’t tell which upstream the request is sent to, and need you to provide the relevant routing configuration.
