### ISSUE TITLE
bug: ApisixRoute backendPoint duplicate

### ISSUE THREAD

**Issue by zlhgo** [apache/apisix-ingress-controller#732]
### Issue description
pkg/kube/translation/apisix_route.go:258
ApisixRoute backendPoint duplicates

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
```bash
→ ./apisix-ingress-controller version --long                                                          
Version: 1.3.0
Git SHA: 65f7c88
Go Version: go1.17.2
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```

* your Kubernetes cluster version (output of `kubectl version`);
```bash
→ kubectl version                                                                                     
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
```bash
→ uname -a                                                                                            
Linux zlh-PC 5.10.60-amd64-desktop #1 SMP Thu Aug 26 18:24:56 CST 2021 x86_64 GNU/Linux
```

### Minimal test code / Steps to reproduce the issue

1. ApisixRoute config
```yaml
apiVersion: apisix.apache.org/v2beta1
kind: ApisixRoute
metadata:
  name: flask-demo
spec:
  http:
  - name: http-8000
    match:
      hosts:
      - flask-demo.local.cn
      paths:
      - /*
    backends:
      - serviceName: flask-demo
        servicePort: 8000
        weight: 100
      - serviceName: flask-demo-group-a
        servicePort: 8000
        weight: 50
      - serviceName: flask-demo-group-b
        servicePort: 8000
        weight: 50
```

### What's the actual result? (including assertion message & call stack if applicable)
![image](https://user-images.githubusercontent.com/3353864/139775809-81509113-2e85-4a4c-832d-e37c0f8accc1.png)

### What's the expected result?
![image](https://user-images.githubusercontent.com/3353864/139776134-496c80fd-5c62-40fb-bb1e-657283fb5b95.png)

### Patch
```diff
diff --git a/pkg/kube/translation/apisix_route.go b/pkg/kube/translation/apisix_route.go
index 9ffee9f..928a7db 100644
--- a/pkg/kube/translation/apisix_route.go
+++ b/pkg/kube/translation/apisix_route.go
@@ -254,8 +254,8 @@ func (t *translator) translateHTTPRouteV2beta1(ctx *TranslateContext, ar *config
                                weight = *backend.Weight
                        }
                        backendPoints := make([]*configv2alpha1.ApisixRouteHTTPBackend, 0)
-                       for _, b := range backends {
-                               backendPoints = append(backendPoints, &b)
+                       for i, _ := range backends {
+                               backendPoints = append(backendPoints, &backends[i])
                        }
                        plugin, err := t.translateTrafficSplitPlugin(ctx, ar.Namespace, weight, backendPoints)
                        if err != nil {
```
