### ISSUE TITLE
request help: how to rewrite path?

### ISSUE THREAD

**Issue by jikunchong** [apache/apisix-ingress-controller#738]
### Issue description
我想将后端服务 httpbin 服务挂在 api.domain.local/httpbin 子路径下。
当我挂在 httpbin.domain.local 可以访问，但挂在 api.domain.local/httpbin 子路径下就不行。

我的配置如下：
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: httpbin-ingress
  namespace: try-apps
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: ''
spec:
  ingressClassName: apisix
  rules:
    - host: api.domain.local
      http:
        paths:
          - path: /httpbin
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 8080
    - host: httpbin.domain.local
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: httpbin
                port:
                  number: 8080
```
请问，我该如何实现类似 nginx.ingress.kubernetes.io/rewrite-target: / 的功能？

### Environment
KubeSphere 3.2.0
MetalLB 0.11.0
apisix-ingress-controller v1.3.0

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
