### ISSUE TITLE
request help: how to access istio services (demo: Bookinfo)？

### ISSUE THREAD

**Issue by jikunchong** [apache/apisix-ingress-controller#750]
### Issue description
我在 KubeSphere 中部署了 istio 的 demo app: Bookinfo，已确认通过 NodePort 方式能正常访问  productpage 微服务。
现在希望通过 apisix-ingress-controller 访问到 Bookinfo productpage，不知是否可行？
有没有类似  nginx.ingress.kubernetes.io/service-upstream: true 的注解配置，或者是更好的推荐配置方式？

### Environment

* your apisix-ingress-controller version (1.3.0);
* your Kubernetes cluster version (1.22.1);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (Linux nuc10 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux).
* KubeSphere 3.2.0
* Istio 1.11.1
* MetalLB 0.11.0 （apisix-gateway 使用 LoadBalancer 方式）

**Comment by tokers** [comment]
@jikunchong See https://apisix.apache.org/docs/ingress-controller/references/apisix_route_v2beta1/#service-resolve-granularity.

**Comment by jikunchong** [comment]
请问有成功的示例吗？我之前部署的 httpbin demo 都能正常生成规则，并在 apisix dashboard 中可以看到，并可以正常访问。
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: httpbin-ingress
  namespace: try-apps
  annotations:
    k8s.apisix.apache.org/rewrite-target-regex: /httpbin/(.*)
    k8s.apisix.apache.org/rewrite-target-regex-template: /$1
    kubesphere.io/alias-name: ''
    kubesphere.io/creator: admin
    kubesphere.io/description: httpbin ingress
spec:
  ingressClassName: apisix
  rules:
    - host: api.domain.local
      http:
        paths:
          - path: /httpbin/
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 8080
```

但换成 istio bookinfo productpage 服务后，就不能生成规则了（访问成果：{"error_msg":"404 Route Not Found"} ）。
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: bookinfo-ingress
  namespace: try-apps
  annotations:
    k8s.apisix.apache.org/rewrite-target-regex: /bookinfo/(.*)
    k8s.apisix.apache.org/rewrite-target-regex-template: /$1
    kubesphere.io/creator: admin
    kubesphere.io/description: ''
spec:
  ingressClassName: apisix
  rules:
    - host: api.domain.local
      http:
        paths:
          - path: /bookinfo/
            pathType: Prefix
            backend:
              service:
                name: productpage
                port:
                  number: 9080
```
所以你说这个 service-resolve-granularity 我也就没法配置。我不知道问题出在哪里了？

**Comment by jikunchong** [comment]
看 apisix ingress controller 的容器日志是这样的：
```
 2021-11-20T17:25:50+08:00	error	apisix/route.go:191	failed to reflect route delete to cache: not found

 2021-11-20T17:25:50+08:00	error	apisix/route.go:161	failed to create route: unexpected status code 400; error message: {"error_msg":"failed to fetch upstream info by upstream id [b3f9690], response code: 404"}

 

 2021-11-20T17:25:50+08:00	error	ingress/ingress.go:178	failed to sync ingress artifacts	{"error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"failed to fetch upstream info by upstream id [b3f9690], response code: 404\"}\n\n\n"}

 2021-11-20T17:25:50+08:00	warn	ingress/ingress.go:191	sync ingress failed, will retry	{"object": {"Type":2,"Object":{"Key":"try-apps/bookinfo-ingress","GroupVersion":"networking/v1","OldObject":{}},"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"failed to fetch upstream info by upstream id [b3f9690], response code: 404\"}\n\n\n"}
```

**Comment by tao12345666333** [comment]
For this kind of scenario, I have tested and available.

I will write a complete article next week to explain the steps.  The key point here is that you need to enable automatic injection of istio for the namespace where apisix is ​​located.

**Comment by tao12345666333** [comment]
like this:


![2021-11-16 15-58-39屏幕截图](https://user-images.githubusercontent.com/3264292/142752004-4174af40-453f-46dc-808a-623fe6c81781.png)

**Comment by jikunchong** [comment]
thanks, I try try

**Comment by jikunchong** [comment]
没成功，请问除了给空间打 istio-injection=enabled 标签外，还需要做什么？
```shell
sudo kubectl label namespace apisix-system istio-injection=enabled
sudo kubectl label namespace try-apps istio-injection=enabled
sudo kubectl get namespace -L istio-injection
NAME                              STATUS   AGE     ISTIO-INJECTION
apisix-system                     Active   17d     enabled
try-apps                          Active   16d     enabled
```
我参考 productpage，手动在 apisix 的 Deployment 加注解，重建 Pod，也没看到 istio-proxy sidecar。
```yaml
metadata:
  name: productpage-v1
  namespace: apisix-system
  # ...
  annotations:
    # ...
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
```
