### ISSUE TITLE
request help: The route name generated by default is too long

### ISSUE THREAD

**Issue by BuptZyc** [apache/apisix-ingress-controller#781]
### Issue description
默认生成的路由名称过长，导致dashboard中无法修改。报错信息如下：
Request Error Code: 10004
input validate failed: Key: 'UpdateInput.Route.Name' Error:Field validation for 'Name' failed on the 'max' tag
想问下有什么地方可以设置默认生成的路由名称吗
### Environment
* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);1.3.0
* your Kubernetes cluster version (output of `kubectl version`);1.16
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tao12345666333** [comment]
There are actually two problems here.

* About modifying the route created by apisix-ingress in the dashboard

**We do not recommend this, or even refuse to do so.** Because this will cause various unexpected problems. When using apisix-ingress, you should ensure that all input is done by manipulating resources in K8s.

* The generated name is too long

Can't be modified at the moment, welcome to submit PR modification.

**Comment by BuptZyc** [comment]
主要是想开启ext-plugin-pre-req使用自定义插件。不推荐修改路由的话，想问下怎么开启插件并进行配置呢

**Comment by han6565** [comment]
我也跟你遇见一样的问题，修改apisix-dashboard源码，他那有个长度验证，改长点就完了，

**Comment by han6565** [comment]
> 

> There are actually two problems here.
> 
> * About modifying the route created by apisix-ingress in the dashboard
> 
> **We do not recommend this, or even refuse to do so.** Because this will cause various unexpected problems. When using apisix-ingress, you should ensure that all input is done by manipulating resources in K8s.
> 
能说下为什么不建议或者拒绝修改route么，比如我要增加或者删除限流插件这种，会有什么问题么，我看ingress-controller 寻找route是根据namespace和service等生成ID，来做两边对照的，如果我在controller生成route后就只在deashboard操作一些插件，只在删除route时再由controller操作，不去碰触upstream和route的其他内容这样也会有问题么。

**Comment by BuptZyc** [comment]
@han6565 自己定义 ApisixRoute 资源就可以了，我试了下没啥问题，插件可以配置，路由名称也能自己指定了。

**Comment by tao12345666333** [comment]
You can using ApisixRoute like this one.
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
 name: httpbin-route
spec:
 http:
 - name: rule1
   match:
     hosts:
     - httpbin.org
     paths:
       - /ip
   backends:
   - serviceName: %s
     servicePort: %d
     weight: 10
   plugins:
   - name: echo
     enable: true
     config:
       before_body: "This is the preface"
       after_body: "This is the epilogue"
       headers:
         X-Foo: v1
         X-Foo2: v2
```
