### ISSUE TITLE
request help: 采用CRD方式，如何通过ApisixRoute配置转发到三方ip:端口服务

### ISSUE THREAD

**Issue by FlonFl** [apache/apisix-ingress-controller#813]
### Issue description

如下方式，通过CRD ApisixRoute是否能够代理到baidu.com?  thanks.
```
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: xxxxx
  namespace: default
spec:
  http:
    - name: apisix-dashboard
      match:
        paths:
          - /xxxx/*
      backends:
        serviceName: http://www.baidu.com   ## like this？
        servicePort: 80
```

### Environment

```
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                    
apisix/apisix                           0.7.2           2.10.0          A Helm chart for Apache APISIX                 
apisix/apisix-dashboard                 0.3.0           2.9.0           A Helm chart for Apache APISIX Dashboard       
apisix/apisix-ingress-controller        0.8.0           1.3.0           Apache APISIX Ingress Controller for Kubernetes
```

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
You can add an ExternalName service.

**Comment by FlonFl** [comment]
> You can add an ExternalName service.

Thanks;  
However I found: I can create "ExternalName service", but can't add into the apisix gateway use "kubectl apply - f" 。

**Comment by tao12345666333** [comment]
> > You can add an ExternalName service.
> 
> 
> 
> Thanks;  
> 
> However I found: I can create "ExternalName service", but can't add into the apisix gateway use "kubectl apply - f" 。
> 
> 

I don't understand.

**Comment by FlonFl** [comment]
> > > You can add an ExternalName service.
> > 
> > 
> > Thanks;
> > However I found: I can create "ExternalName service", but can't add into the apisix gateway use "kubectl apply - f" 。
> 
> I don't understand.

My ApisixRoute  "ar.yaml" (Namespace is “default”) : 
```
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: sd
spec:
  http:
    - name: sd_1
      match:
        hosts: 
          - xx.xxx.com
        paths:
          - /*
      backends:
        - serviceName: bdsvc   # This is ExternalName service
          servicePort: 80
```
Used :
kubectl apply - f ar.yaml

But,  I can't see route and upstream from the dashboard. 
通过配置后，我不能从ApisixGateway控制台看到配置的ApisixRoute，其他的非ExternalName service却能够看到，且能访问到。

And, I use K3S.  
Thanks.
我使用的是K3S环境，非K8S，期待您的解答，谢谢。
