### ISSUE TITLE
request help: How to configure ApisixPluginConfig？

### ISSUE THREAD

**Issue by yin6516008** [apache/apisix-ingress-controller#854]
### Issue description

CRD resource configuration files：
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixPluginConfig
metadata:
  name: openapi-auth
  namespace: default
spec:
  plugins:
    - name: authz-casbin
      enable: true
      config:
        model_path: "/usr/local/apisix/conf/casbin-model.conf"
        policy: "test, /*,GET"
        username: "user"
```

apisix-ingress-controller log:
`2022-02-08T09:43:51+08:00	[33mwarn[0m	ingress/apisix_pluginconfig.go:224	sync ApisixPluginConfig failed, will retry	{"object": {"Type":2,"Object":{"Key":"default/openapi-auth","OldObject":{},"GroupVersion":"apisix.apache.org/v2beta3"},"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"failed to check the configuration of plugin authz-casbin err: value should match only one schema, but matches none\"}\n\n\n"}`

Is the CRD configuration fields is there a problem？

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4
- your Kubernetes cluster version (output of kubectl version): 1.20
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): centos7.6

**Comment by tokers** [comment]
@yin6516008 The reason is the config of `authz-casbin` is not correct, it doesn't match the jsonschema requirements.

@tao12345666333 We don't have strong check for plugin config? I think we need to strengthen it.

**Comment by yin6516008** [comment]
I create succeeded in using the following way：
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixPluginConfig
metadata:
  name: openapi-auth
  namespace: default
spec:
  plugins:
    - name: authz-casbin
      enable: true
      config:
        model: "[request_definition]\nr = sub, obj, act\n[policy_definition]\np = sub, obj, act\n[role_definition]\ng = _, _\n[policy_effect]\ne = some(where (p.eft == allow))\n[matchers]\nm = g(r.sub, p.sub) && globMatch(r.obj,p.obj) && regexMatch(r.act,p.act)"
        policy: "p, test, /*, *\np,test2 /*, GET"
        username: "user"
```
```bash
/ingress-apisix # curl "http://apisix-admin.apisix.svc.cluster.local:9180/apisix/admin/plugin_configs" -H 'X-API-KEY: edxxxxxxxxxxxxxxx25c8f1'
{"count":1,"node":{"key":"\/apisix\/plugin_configs","dir":true,"nodes":[{"key":"\/apisix\/plugin_configs\/6191bd21","value":{"plugins":{"authz-casbin":{"model":"[request_definition]\nr = sub, obj, act\n[policy_definition]\np = sub, obj, act\n[role_definition]\ng = _, _\n[policy_effect]\ne = some(where (p.eft == allow))\n[matchers]\nm = g(r.sub, p.sub) && globMatch(r.obj,p.obj) && regexMatch(r.act,p.act)","policy":"p, test, \/foo, GET\np,test2 \/bar, GET","username":"user"}},"labels":{"managed-by":"apisix-ingress-controller"},"id":"6191bd21","update_time":1644314331,"name":"default_openapi-auth","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","create_time":1644311280},"modifiedIndex":62,"createdIndex":41}]},"action":"get"}
```

create a consumer
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixConsumer
metadata:
  name: test
  namespace: default
spec:
  authParameter:
    keyAuth: 
      value: 
        key: ZTLb3X1qmf5e
```
```bash
/ingress-apisix # curl "http://apisix-admin.apisix.svc.cluster.local:9180/apisix/admin/consumers" -H 'X-API-KEY: edxxxxxxxxxxxxc8f1'
{"count":1,"node":{"key":"\/apisix\/consumers","dir":true,"nodes":[{"key":"\/apisix\/consumers\/default_test","value":{"plugins":{"key-auth":{"key":"ZTLb3X1qmf5e"}},"labels":{"managed-by":"apisix-ingress-controller"},"desc":"Created by apisix-ingress-controller, DO NOT modify it manually","update_time":1644228859,"username":"default_test","create_time":1644228859},"modifiedIndex":38,"createdIndex":38}]},"action":"get"}
```

But when I quote this plugin in routing, don't take effect.
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: echo
  namespace: default
spec:
  http:
  - name: echo
    match:
      hosts:
      - echo.jc-ai.cn
      paths:
      - /*
    plugin_config_name: openapi-auth
    backends:
      - serviceName: echo
        servicePort: 8080
```

plugin config is not in the route:
```bash
curl "http://apisix-admin.apisix.svc.cluster.local:9180/apisix/admin/routes/f2035783" -H 'X-API-KEY: ecccccccccxxcc5c8f1'
{"count":1,"node":{"key":"\/apisix\/routes\/f2035783","value":{"name":"default_echo_echo","id":"f2035783","priority":0,"upstream_id":"e4f10124","labels":{"managed-by":"apisix-ingress-controller"},"create_time":1644313158,"update_time":1644313158,"uris":["\/*"],"desc":"Created by apisix-ingress-controller, DO NOT modify it manually","status":1,"hosts":["echo.jc-ai.cn"]}},"action":"get"}
```

Don`t take request header  also can get to success. 
```bash
[root@skywalking ~]# curl echo.jc-ai.cn/foo


Hostname: echo-5ddc95c657-4m85q

Pod Information:
        -no pod information available-

Server values:
        server_version=nginx: 1.14.2 - lua: 10015

Request Information:
        client_address=172.30.0.57
        method=GET
        real path=/foo
        query=
        request_version=1.1
        request_scheme=http
        request_uri=http://echo.jc-ai.cn:8080/foo

Request Headers:
        accept=*/*
        host=echo.jc-ai.cn
        user-agent=curl/7.29.0
        x-forwarded-for=172.30.0.1
        x-forwarded-host=echo.jc-ai.cn
        x-forwarded-port=9080
        x-forwarded-proto=http
        x-real-ip=172.30.0.1

Request Body:
        -no body in request-

```

Why response status code is not 401?

**Comment by tao12345666333** [comment]
let me check it.

**Comment by yin6516008** [comment]
I'm sorry, I won't be free debugging it recently。

apply
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: echo
  namespace: default
spec:
  http:
  - name: echo
    match:
      hosts:
      - echo.jc-ai.cn
      paths:
      - /*
    plugin_config_name: openapi-auth
    backends:
      - serviceName: echo
        servicePort: 8080
```

```bash
# kubectl describe  apisixroute  echo 
Name:         echo
Namespace:    default
Labels:       <none>
Annotations:  API Version:  apisix.apache.org/v2beta3
Kind:         ApisixRoute
Metadata:
  Creation Timestamp:  2022-03-03T06:47:27Z
  Generation:          1
  Resource Version:    29884427
  UID:                 fa77ba15-5ccf-4c54-b87d-7516f6a120e4
Spec:
  Http:
    Backends:
      Service Name:  echo
      Service Port:  8080
    Match:
      Hosts:
        echo.jc-ai.cn
      Paths:
        /*
    Name:  echo
Status:
  Conditions:
    Message:              Sync Successfully
    Observed Generation:  1
    Reason:               ResourcesSynced
    Status:               True
    Type:                 ResourcesAvailable
Events:
  Type    Reason           Age                From           Message
  ----    ------           ----               ----           -------
  Normal  ResourcesSynced  11m (x2 over 11m)  ApisixIngress  ApisixIngress synced successfully
```
Why are there no plugin_config_name field？

**Comment by tao12345666333** [comment]
@yin6516008  How was your CRD installed?

Can you use this CRD? https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml

**Comment by yin6516008** [comment]
![image](https://user-images.githubusercontent.com/23651702/156710894-940aea93-a47f-4921-8810-cfd1e05894dc.png)

I use the latest crd file. but apisixroute dispaly v2beta1.  I delete v2betav1、v2betav2 in the apisixroute, apply the route agin, the plugin_config_name appeared.

Let's ignore the situation above. to pay attention to the following questions
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixPluginConfig
metadata:
  name: openapi-auth
  namespace: default
spec:
  plugins:
    - name: authz-casbin
      enable: true
      config:
        model: "[request_definition]\nr = sub, obj, act\n[policy_definition]\np = sub, obj, act\n[role_definition]\ng = _, _\n[policy_effect]\ne = some(where (p.eft == allow))\n[matchers]\nm = g(r.sub, p.sub) && globMatch(r.obj,p.obj) && regexMatch(r.act,p.act)"
        policy: "p,test,/foo,POST\np,test2,/bar,POST"
        username: "user"
```
When I apply this file, apisix-ingress-controller got below error
```bash
2022-03-04T14:35:14+08:00	info	ingress/controller.go:609	service kube-system/ccm not found
W0304 14:35:15.141661       1 reflector.go:441] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: watch of *v2beta3.ApisixPluginConfig ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"ApisixPluginConfig\" is registered for version \"apisix.apache.org/v2beta3\" in scheme \"pkg/runtime/scheme.go:100\"") has prevented the request from succeeding
[GIN] 2022/03/04 - 14:35:15 | 200 |       34.34µs |      172.30.0.1 | GET      "/healthz"
W0304 14:35:16.287189       1 reflector.go:441] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: watch of *v2beta3.ApisixPluginConfig ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"ApisixPluginConfig\" is registered for version \"apisix.apache.org/v2beta3\" in scheme \"pkg/runtime/scheme.go:100\"") has prevented the request from succeeding
2022-03-04T14:35:16+08:00	info	ingress/controller.go:609	service kube-system/ccm not found
```
I have tried many ways to no avail. Is there a problem with the format?

**Comment by tao12345666333** [comment]
> ![image](https://user-images.githubusercontent.com/23651702/156710894-940aea93-a47f-4921-8810-cfd1e05894dc.png)
> 
> 
> 
> I use the latest crd file. but apisixroute dispaly v2beta1.  I delete v2betav1、v2betav2 in the apisixroute, apply the route agin, the plugin_config_name appeared.
> 
> 
> 

The CRD version is the cause of the problem.

This feature was only introduced in the latest version.


As for the second question you mentioned, we will use the #817 for tracking

**Comment by tao12345666333** [comment]
In previous versions, it can be configured as follows

```

apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
 name: httpbin-route
spec:
 http:
 - name: rule1
   match:
     hosts:
     - httpbin.org
     paths:
       - /ip
   backends:
   - serviceName: foo
     servicePort: 9090
     weight: 10
   plugins:
   - name: xxxx
     enable: true
     config:
       Xxxx 

```
