### ISSUE TITLE
suggest：proxy scheme should be in ApisixRoute not ApisixUpstream

### ISSUE THREAD

**Issue by myselfghost** [apache/apisix-ingress-controller#871]
why:  In most scenarios, we only need to define a ApisixRoute, and we don't need to bother to define ApisixUpstream. but, if we proxy a grpc service , we have to define ApisixUpstream like 

```
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: yages
  namespace: ingress-apisix
spec:
  scheme: grpc
```
so suggest：proxy scheme should be in ApisixRoute not ApisixUpstream, that way we can do less work
