### ISSUE TITLE
feat request: native MQTT Protocol  proxy  

### ISSUE THREAD

**Issue by siaron** [apache/apisix-ingress-controller#966]
### Issue description

- Native support for MQTT protocol brokers. like tcp Route
- Load balancing based on client_id
- The mqtt broker is deployed in the k8s environment. Dynamically capture pod creation and deletion. And update upstream

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
This is a feature request and I modified the title.

Can you describe your specific scenario? Do you directly expose Ingress to clients in your business scenario?

**Comment by siaron** [comment]
> This is a feature request and I modified the title.
> 
> Can you describe your specific scenario? Do you directly expose Ingress to clients in your business scenario?

IoT scenario . Many devices connect to the emqx cluster deployed on k8s through a proxy(apisix/haproxy). on aliyun. Expose only one tcp port of apisix-ingress

**Comment by stillfox-lee** [comment]
WeOpen Star
I'm willing to help implement this feature, but i m not sure is suitable for me. I have no experience at any ingress controller development.
I find out APISIX has support MQTT protocol by `mqtt-proxy` plugin. So ApisixIngress just need to implement `stream[].plugins` at ApisixRoute API? Is three any guideline about how to implement APISIX's stream plugin?

**Comment by tokers** [comment]
> WeOpen Star I'm willing to help implement this feature, but i m not sure is suitable for me. I have no experience at any ingress controller development. I find out APISIX has support MQTT protocol by `mqtt-proxy` plugin. So ApisixIngress just need to implement `stream[].plugins` at ApisixRoute API? Is three any guideline about how to implement APISIX's stream plugin?

Right. What you should focus on are:
 * What fields should we expose in the CRD?
 * How to generate the plugin config on the  APISIX side.
 
 You can refer to some existing plugin supports (Now APISIX Ingress Controller doesn't customize fields on the CRD side but use same plugin settings with APISIX).

**Comment by tao12345666333** [comment]
@stillfox-lee Assigned, thanks.

**Comment by stillfox-lee** [comment]
Hi guys. I have some question about this feature:

 First, which version should this feature support?

- [ ] v1
- [ ] v2
- [ ] v2beta2
- [ ] v2beta3

Second, should we use `annotation` or `stream[].plugins` in yaml to defined `mqtt-proxy` plugin? Or both?

In `annotation` way, we can write yaml like this:

```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  annotations:
  k8s.apisix.apache.org/mqtt-proxy-name: "MQTT"
  k8s.apisix.apache.org/mqtt-proxy-level: "5"
  name: ***
spec:
  stream:
  - name: ***
    protocol: TCP
    match: 
      ingressPort: 9100
    backends:
    - serviceName: mqtt-service
       servicePort: 9200
```

In `stream[].plugins` way, we can write yaml like this:
```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: ***
spec:
  stream:
  - name: ***
    protocol: TCP
    match: 
      ingressPort: 9100
    backends:
    - serviceName: mqtt-service
       servicePort: 9200
    plugins:
    - name: mqtt-proxy
      enable: true
      config:
        protocolName: MQTT
        protocolLevel: 4
```

If i misunderstand Apisix Ingress Controller mechanism, please tell me, thanks.
