### ISSUE TITLE
request help: crd resource does not display correctly when using Lens

### ISSUE THREAD

**Issue by Horus-K** [apache/apisix-ingress-controller#979]
### Issue description

![image](https://user-images.githubusercontent.com/48319268/164610584-ae70eead-a209-4cba-a68c-79da98cdff01.png)
![image](https://user-images.githubusercontent.com/48319268/164610649-832a3122-e30e-4573-b108-0d7f41ebdf75.png)
i use this crd https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: rancher
  namespace: cattle-system
spec:
  http:
  - backends:
    - resolveGranularity: endpoint
      serviceName: rancher
      servicePort: 80
      weight: 100
    match:
      hosts:
      - xx.xxxx.com
      paths:
      - /*
    name: rule11
    websocket: true
status:
  conditions:
  - message: Sync Successfully
    observedGeneration: 3
    reason: ResourcesSynced
    status: "True"
    type: ResourcesAvailable
```
```
# log options
log_level: "info"
log_output: "stderr"
cert_file: "/etc/webhook/certs/cert.pem"
key_file: "/etc/webhook/certs/key.pem"
http_listen: ":8080"
https_listen: ":8443"
ingress_publish_service: 
enable_profiling: true
kubernetes:
  kubeconfig: ""
  resync_interval: "6h"
  app_namespaces:
  - "*"
  namespace_selector:
  - ""
  election_id: "ingress-apisix-leader"
  ingress_class: "apisix"
  ingress_version: "networking/v1"
  watch_endpointslices: false
  apisix_route_version: "apisix.apache.org/v2beta3"
  enable_gateway_api: false
apisix:
  default_cluster_base_url: http://apisix-admin.apisix.svc.cluster.local:9180/apisix/admin
  default_cluster_admin_key: "xxxxxx"
  default_cluster_name: "apisix"
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.4
- your Kubernetes cluster version (output of kubectl version): tke 1.20.6
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
