### ISSUE TITLE
Doc: description in the document about the scheme is not up to date

### ISSUE THREAD

**Issue by Chever-John** [apache/apisix-ingress-controller#982]
Now we support HTTPS protocol, but the document is not up to date.

Click this [link](https://apisix.apache.org/zh/docs/ingress-controller/references/apisix_upstream#:~:text=CHANGELOG-,ApisixUpstream%20Reference,-Field) and you will see:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/43690894/164956879-61d484cd-9599-4916-ac02-332b709ae7e7.png">

Hope for someone to solve this!

**Comment by tao12345666333** [comment]
we support http/https and gRPC/gRPCs

**Comment by wangyp0701** [comment]
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: mgr-dashboard
spec:
  scheme: https
```
