### ISSUE TITLE
request help: support wolf-rbac plugin for ApisixConsumer

### ISSUE THREAD

**Issue by rjiang-ptm** [apache/apisix-ingress-controller#986]
### Issue description

In Kubernetes, we want to use CR ApisixConsumer to create a consumer in apisix. However, it seems to only support `basicAuth` and `keyAuth`? 

Using apisix admin api to create consumer directly does work, however, we'd like to use CR via apisix ingress controller if possible.

When I tried to use `wolf-rbac` as the auth plugin, eg.

```
apiVersion: apisix.apache.org/v2alpha1
kind: ApisixConsumer
metadata:
  name: cluster-admin-ac
spec:
  authParameter:
    wolf-rbac:
      value: "http://component-wolf-rbac.infra-wolf-rbac:12180"
      key: "server"
      value: "tensor"
      key: "appid"
```
I got `error validating data: ValidationError(ApisixConsumer.spec.authParameter): unknown field "wolf-rbac" in org.apache.apisix.v2alpha1.ApisixConsumer.spec.authParameter; if you choose to ignore these errors, turn validation off with --validate=false`

Or is there a different way to specify auth plugins? I couldn't find document on more examples to use ApisixConsumer CR either...

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.2.0
- your Kubernetes cluster version (output of kubectl version): 1.19
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
